# Generated by Django 4.2.7 on 2026-06-18 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('exterior', '外观'), ('interior', '内饰'), ('engine', '发动机'), ('chassis', '底盘'), ('electric', '电器系统'), ('tires', '轮胎'), ('brakes', '制动系统'), ('suspension', '悬挂系统'), ('airbag', '安全气囊'), ('accident', '事故痕迹'), ('water_damage', '泡水痕迹'), ('fire_damage', '火烧痕迹')], max_length=30, verbose_name='检测项')),
                ('rating', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('average', '一般'), ('poor', '较差'), ('bad', '严重')], default='good', max_length=20, verbose_name='评级')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='照片列表')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '检测项结果',
                'verbose_name_plural': '检测项结果',
            },
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_no', models.CharField(max_length=50, unique=True, verbose_name='检测单号')),
                ('status', models.CharField(choices=[('pending', '待检测'), ('in_progress', '检测中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='检测状态')),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='检测时里程')),
                ('overall_rating', models.CharField(blank=True, choices=[('excellent', '优秀'), ('good', '良好'), ('average', '一般'), ('poor', '较差'), ('bad', '严重')], max_length=20, verbose_name='综合评级')),
                ('has_accident', models.BooleanField(default=False, verbose_name='是否事故车')),
                ('has_water_damage', models.BooleanField(default=False, verbose_name='是否泡水车')),
                ('has_fire_damage', models.BooleanField(default=False, verbose_name='是否火烧车')),
                ('has_structural_damage', models.BooleanField(default=False, verbose_name='是否结构性损伤')),
                ('general_condition', models.TextField(blank=True, verbose_name='车况总结')),
                ('issues', models.TextField(blank=True, verbose_name='存在问题')),
                ('suggestions', models.TextField(blank=True, verbose_name='建议')),
                ('verified', models.BooleanField(default=False, verbose_name='是否已复核')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('inspection_date', models.DateField(default=django.utils.timezone.now, verbose_name='检测日期')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '检测报告',
                'verbose_name_plural': '检测报告',
                'ordering': ['-created_at'],
            },
        ),
    ]
