# Generated by Django 4.2.7 on 2026-06-18 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='检测师'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_report', to='vehicles.vehicle', verbose_name='车源'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_inspections', to=settings.AUTH_USER_MODEL, verbose_name='复核人'),
        ),
        migrations.AddField(
            model_name='inspectionitemresult',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.inspectionreport', verbose_name='检测报告'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectionitemresult',
            unique_together={('report', 'item')},
        ),
    ]
