# Generated by Django 4.2.7 on 2026-06-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('class_name', models.CharField(blank=True, default='', max_length=100, verbose_name='班级')),
                ('contact', models.CharField(blank=True, default='', max_length=50, verbose_name='联系方式')),
                ('guardian_contact', models.CharField(blank=True, default='', max_length=50, verbose_name='监护人联系方式')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员',
                'db_table': 'student',
                'ordering': ['id'],
            },
        ),
    ]
