# Generated by Django 4.2.7 on 2026-06-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', '在读'), ('graduated', '已结业'), ('transferred', '已转出'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='idx_student_status'),
        ),
    ]
