// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import ModalController from "./modal_controller"
import TodoController from "./todo_controller"
import ChartController from "./chart_controller"
import FilterController from "./filter_controller"
import DatatableController from "./datatable_controller"

application.register("hello", HelloController)
application.register("modal", ModalController)
application.register("todo", TodoController)
application.register("chart", ChartController)
application.register("filter", FilterController)
application.register("datatable", DatatableController)
