// This file is auto-generated by @hotwired/stimulus-webpack-helpers
// and will be regenerated by the Stimulus generator.

import { application } from "./application"

// Import all controllers from the controllers directory
// Eager load all controllers defined in the import map under controllers/**/*_controller
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)
