# Generated by Django 4.2.7 on 2026-06-18 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('appearance', '外观整备'), ('interior', '内饰清洁'), ('mechanical', '机械维修'), ('electric', '电气维修'), ('paint', '喷漆修复'), ('tire', '轮胎更换'), ('detailing', '精细美容'), ('other', '其他')], max_length=30, verbose_name='整备类别')),
                ('name', models.CharField(max_length=200, verbose_name='整备项目')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预估费用(元)')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际费用(元)')),
                ('is_done', models.BooleanField(default=False, verbose_name='是否完成')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='前后对比照片')),
            ],
            options={
                'verbose_name': '整备项目',
                'verbose_name_plural': '整备项目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PreparationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='整备单号')),
                ('status', models.CharField(choices=[('pending', '待整备'), ('in_progress', '整备中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='整备状态')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预估费用(元)')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际费用(元)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('verified', models.BooleanField(default=False, verbose_name='是否已复核')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '整备工单',
                'verbose_name_plural': '整备工单',
                'ordering': ['-created_at'],
            },
        ),
    ]
