# Generated by Django 4.2.7 on 2026-06-18 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preparations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationorder',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparations', to=settings.AUTH_USER_MODEL, verbose_name='整备负责人'),
        ),
        migrations.AddField(
            model_name='preparationorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_orders', to='vehicles.vehicle', verbose_name='车源'),
        ),
        migrations.AddField(
            model_name='preparationorder',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_preparations', to=settings.AUTH_USER_MODEL, verbose_name='复核人'),
        ),
        migrations.AddField(
            model_name='preparationitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='preparations.preparationorder', verbose_name='整备工单'),
        ),
    ]
