<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AutoRepair.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.6" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoRepair.Application\AutoRepair.Application.csproj" />
    <ProjectReference Include="..\AutoRepair.Infrastructure\AutoRepair.Infrastructure.csproj" />
    <ProjectReference Include="..\AutoRepair.Domain\AutoRepair.Domain.csproj" />
  </ItemGroup>

</Project>
