# Generated by Django 4.2.7 on 2026-06-15 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=10, verbose_name='风险等级')),
                ('reason', models.TextField(blank=True, default='', verbose_name='风险原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_records', to='distributions.distribution', verbose_name='发放记录')),
            ],
            options={
                'verbose_name': '风险记录',
                'verbose_name_plural': '风险记录',
                'db_table': 'risk_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.TextField(verbose_name='复核结论')),
                ('reviewer_id', models.IntegerField(blank=True, null=True, verbose_name='复核人ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_conclusions', to='risk.riskrecord', verbose_name='风险记录')),
            ],
            options={
                'verbose_name': '复核结论',
                'verbose_name_plural': '复核结论',
                'db_table': 'review_conclusion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='沟通内容')),
                ('comm_type', models.CharField(choices=[('phone', '电话'), ('email', '邮件'), ('in_person', '面谈'), ('online', '线上')], max_length=20, verbose_name='沟通方式')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='创建人ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='risk.riskrecord', verbose_name='风险记录')),
            ],
            options={
                'verbose_name': '沟通记录',
                'verbose_name_plural': '沟通记录',
                'db_table': 'communication',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='riskrecord',
            index=models.Index(fields=['risk_level'], name='idx_risk_record_level'),
        ),
    ]
