// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AutoRepair.Infrastructure.Data;

#nullable disable

namespace AutoRepair.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250101000000_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // === Identity tables ===
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.HasKey("Id");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");
                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.HasKey("LoginProvider", "ProviderKey");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");
                    b.HasKey("UserId", "RoleId");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");
                    b.HasKey("UserId", "LoginProvider", "Name");
                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");
                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");
                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");
                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");
                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");
                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");
                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");
                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");
                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");
                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");
                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.CommunicationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("FromUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<Guid?>("QuoteId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");
                    b.Property<Guid?>("StockAlertId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("ToUserId")
                        .HasColumnType("nvarchar(450)");
                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("FromUserId");
                    b.HasIndex("QuoteId");
                    b.HasIndex("StockAlertId");
                    b.HasIndex("ToUserId");
                    b.HasIndex("WorkOrderId");
                    b.ToTable("CommunicationLogs");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.Diagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<DateTime>("DiagnosedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("DiagnosedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("DiagnosticResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("FaultCodes")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Recommendations")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("SymptomDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("DiagnosedByUserId");
                    b.HasIndex("VehicleId");
                    b.HasIndex("WorkOrderId");
                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.MaintenanceReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");
                    b.Property<int?>("DueMileage")
                        .HasColumnType("int");
                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");
                    b.Property<bool>("IsNotified")
                        .HasColumnType("bit");
                    b.Property<DateTime?>("NotificationDate")
                        .HasColumnType("datetime2");
                    b.Property<string>("ReminderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("VehicleId");
                    b.ToTable("MaintenanceReminders");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)");
                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("PartNumber")
                        .IsUnique();
                    b.ToTable("Parts");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.PartInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");
                    b.Property<Guid>("PartId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");
                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");
                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("PartId")
                        .IsUnique();
                    b.ToTable("PartInventories");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("CustomerNotes")
                        .HasColumnType("nvarchar(max)");
                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");
                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");
                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)");
                    b.Property<decimal>("LaborTotal")
                        .HasColumnType("decimal(18,2)");
                    b.Property<decimal>("PartsTotal")
                        .HasColumnType("decimal(18,2)");
                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.Property<int>("Status")
                        .HasColumnType("int");
                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");
                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("CreatedByUserId");
                    b.HasIndex("QuoteNumber")
                        .IsUnique();
                    b.HasIndex("WorkOrderId");
                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.QuoteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsPart")
                        .HasColumnType("bit");
                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<decimal>("LaborCost")
                        .HasColumnType("decimal(18,2)");
                    b.Property<Guid?>("PartId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<int>("Quantity")
                        .HasColumnType("int");
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");
                    b.HasKey("Id");
                    b.HasIndex("PartId");
                    b.HasIndex("QuoteId");
                    b.ToTable("QuoteItems");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.ReviewOpinion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");
                    b.Property<string>("Opinion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<Guid?>("QuoteId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("ReviewerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.Property<Guid?>("StockAlertId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("QuoteId");
                    b.HasIndex("ReviewerUserId");
                    b.HasIndex("StockAlertId");
                    b.HasIndex("WorkOrderId");
                    b.ToTable("ReviewOpinions");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.StockAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("AcknowledgedByUserId")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("AlertMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");
                    b.Property<Guid>("PartInventoryId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("AcknowledgedByUserId");
                    b.HasIndex("PartInventoryId");
                    b.ToTable("StockAlerts");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("datetime2");
                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.Property<int>("ManufactureYear")
                        .HasColumnType("int");
                    b.Property<int>("Mileage")
                        .HasColumnType("int");
                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<int?>("NextMaintenanceMileage")
                        .HasColumnType("int");
                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("OwnerPhone")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Series")
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("VinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.HasKey("Id");
                    b.HasIndex("LicensePlate")
                        .IsUnique();
                    b.HasIndex("VinCode")
                        .IsUnique();
                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("AssignedToUserId")
                        .HasColumnType("nvarchar(450)");
                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsRework")
                        .HasColumnType("bit");
                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.Property<Guid?>("OriginalOrderId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");
                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");
                    b.Property<int>("Status")
                        .HasColumnType("int");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("AssignedToUserId");
                    b.HasIndex("OrderNumber")
                        .IsUnique();
                    b.HasIndex("OriginalOrderId");
                    b.HasIndex("VehicleId");
                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.WorkOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");
                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<decimal>("LaborCost")
                        .HasColumnType("decimal(18,2)");
                    b.Property<Guid?>("PartId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<int>("Quantity")
                        .HasColumnType("int");
                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");
                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("PartId");
                    b.HasIndex("WorkOrderId");
                    b.ToTable("WorkOrderItems");
                });

            // === Relationships ===
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AutoRepair.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AutoRepair.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("AutoRepair.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AutoRepair.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.CommunicationLog", b =>
                {
                    b.HasOne("AutoRepair.Domain.Entities.AppUser", "FromUser")
                        .WithMany("SentMessages")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("AutoRepair.Domain.Entities.Quote", "Quote")
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("AutoRepair.Domain.Entities.StockAlert", "StockAlert")
                        .WithMany("CommunicationLogs")
                        .HasForeignKey("StockAlertId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("AutoRepair.Domain.Entities.AppUser", "ToUser")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("AutoRepair.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("FromUser");
                    b.Navigation("Quote");
                    b.Navigation("StockAlert");
                    b.Navigation("ToUser");
                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.Diagnosis", b =>
                {
                    b.HasOne("AutoRepair.Domain.Entities.AppUser", "DiagnosedByUser")
                        .WithMany("Diagnoses")
                        .HasForeignKey("DiagnosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("AutoRepair.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Diagnoses")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("AutoRepair.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Diagnoses")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("DiagnosedByUser");
                    b.Navigation("Vehicle");
                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.MaintenanceReminder", b =>
                {
                    b.HasOne("AutoRepair.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.PartInventory", b =>
                {
                    b.HasOne("AutoRepair.Domain.Entities.Part", "Part")
                        .WithOne("Inventory")
                        .HasForeignKey("AutoRepair.Domain.Entities.PartInventory", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Part");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.Quote", b =>
                {
                    b.HasOne("AutoRepair.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany("CreatedQuotes")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("AutoRepair.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Quotes")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("CreatedByUser");
                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.QuoteItem", b =>
                {
                    b.HasOne("AutoRepair.Domain.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("AutoRepair.Domain.Entities.Quote", "Quote")
                        .WithMany("Items")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Part");
                    b.Navigation("Quote");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.ReviewOpinion", b =>
                {
                    b.HasOne("AutoRepair.Domain.Entities.Quote", "Quote")
                        .WithMany("ReviewOpinions")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade);
                    b.HasOne("AutoRepair.Domain.Entities.AppUser", "ReviewerUser")
                        .WithMany("ReviewOpinions")
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("AutoRepair.Domain.Entities.StockAlert", "StockAlert")
                        .WithMany("ReviewOpinions")
                        .HasForeignKey("StockAlertId")
                        .OnDelete(DeleteBehavior.Cascade);
                    b.HasOne("AutoRepair.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Quote");
                    b.Navigation("ReviewerUser");
                    b.Navigation("StockAlert");
                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.StockAlert", b =>
                {
                    b.HasOne("AutoRepair.Domain.Entities.AppUser", "AcknowledgedByUser")
                        .WithMany()
                        .HasForeignKey("AcknowledgedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("AutoRepair.Domain.Entities.PartInventory", "PartInventory")
                        .WithMany("StockAlerts")
                        .HasForeignKey("PartInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("AcknowledgedByUser");
                    b.Navigation("PartInventory");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("AutoRepair.Domain.Entities.AppUser", "AssignedToUser")
                        .WithMany("AssignedWorkOrders")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("AutoRepair.Domain.Entities.WorkOrder", "OriginalOrder")
                        .WithMany()
                        .HasForeignKey("OriginalOrderId");
                    b.HasOne("AutoRepair.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("WorkOrders")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("AssignedToUser");
                    b.Navigation("OriginalOrder");
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.WorkOrderItem", b =>
                {
                    b.HasOne("AutoRepair.Domain.Entities.Part", "Part")
                        .WithMany("WorkOrderItems")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("AutoRepair.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Items")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Part");
                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.Part", b =>
                {
                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.Quote", b =>
                {
                    b.Navigation("Items");
                    b.Navigation("ReviewOpinions");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.StockAlert", b =>
                {
                    b.Navigation("CommunicationLogs");
                    b.Navigation("ReviewOpinions");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Diagnoses");
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.WorkOrder", b =>
                {
                    b.Navigation("Diagnoses");
                    b.Navigation("Items");
                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("AutoRepair.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("AssignedWorkOrders");
                    b.Navigation("CreatedQuotes");
                    b.Navigation("Diagnoses");
                    b.Navigation("ReceivedMessages");
                    b.Navigation("ReviewOpinions");
                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
