from app.routers import auth
from app.routers import elders
from app.routers import medications
from app.routers import visits
from app.routers import activities
from app.routers import risks
from app.routers import incidents
from app.routers import audit
from app.routers import exports
