import { UserRole, Permission } from '@/lib/api/types';

export const rolePermissions: Record<UserRole, Permission[]> = {
  [UserRole.AUDITOR]: [
    Permission.TASK_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_EDIT,
    Permission.EVIDENCE_VIEW,
    Permission.EVIDENCE_UPLOAD,
    Permission.EVIDENCE_EDIT,
    Permission.CHECKLIST_VIEW,
    Permission.SAMPLING_VIEW,
    Permission.SAMPLING_EDIT,
    Permission.AUDIT_LOG_VIEW,
    Permission.STATISTICS_VIEW,
  ],

  [UserRole.BUSINESS_OWNER]: [
    Permission.TASK_VIEW,
    Permission.EVIDENCE_VIEW,
    Permission.EVIDENCE_UPLOAD,
    Permission.REVIEW_CONDUCT,
    Permission.CHECKLIST_VIEW,
    Permission.SAMPLING_VIEW,
    Permission.AUDIT_LOG_VIEW,
    Permission.STATISTICS_VIEW,
  ],

  [UserRole.COMPLIANCE_OFFICER]: [
    Permission.TASK_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_EDIT,
    Permission.TASK_ASSIGN,
    Permission.TASK_DELETE,
    Permission.EVIDENCE_VIEW,
    Permission.EVIDENCE_UPLOAD,
    Permission.EVIDENCE_EDIT,
    Permission.EVIDENCE_DELETE,
    Permission.REVIEW_CONDUCT,
    Permission.CHECKLIST_VIEW,
    Permission.CHECKLIST_EDIT,
    Permission.SAMPLING_VIEW,
    Permission.SAMPLING_EDIT,
    Permission.AUDIT_LOG_VIEW,
    Permission.STATISTICS_VIEW,
    Permission.UNAUTHORIZED_VIEW,
  ],

  [UserRole.MANAGEMENT]: [
    Permission.TASK_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_EDIT,
    Permission.TASK_ASSIGN,
    Permission.TASK_DELETE,
    Permission.EVIDENCE_VIEW,
    Permission.EVIDENCE_UPLOAD,
    Permission.EVIDENCE_EDIT,
    Permission.EVIDENCE_DELETE,
    Permission.REVIEW_CONDUCT,
    Permission.CHECKLIST_VIEW,
    Permission.CHECKLIST_EDIT,
    Permission.SAMPLING_VIEW,
    Permission.SAMPLING_EDIT,
    Permission.AUDIT_LOG_VIEW,
    Permission.STATISTICS_VIEW,
    Permission.UNAUTHORIZED_VIEW,
    Permission.USER_MANAGE,
  ],

  [UserRole.ADMIN]: [
    Permission.TASK_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_EDIT,
    Permission.TASK_ASSIGN,
    Permission.TASK_BATCH_UPDATE,
    Permission.TASK_DELETE,
    Permission.EVIDENCE_VIEW,
    Permission.EVIDENCE_CREATE,
    Permission.EVIDENCE_UPLOAD,
    Permission.EVIDENCE_EDIT,
    Permission.EVIDENCE_SUBMIT,
    Permission.EVIDENCE_DELETE,
    Permission.REVIEW_CONDUCT,
    Permission.REVIEW_APPROVE,
    Permission.REVIEW_REJECT,
    Permission.REVIEW_VIEW,
    Permission.CHECKLIST_CREATE,
    Permission.CHECKLIST_VIEW,
    Permission.CHECKLIST_EDIT,
    Permission.CHECKLIST_EXECUTE,
    Permission.SAMPLING_CREATE,
    Permission.SAMPLING_VIEW,
    Permission.SAMPLING_EDIT,
    Permission.SAMPLING_APPROVE,
    Permission.TEMPLATE_CREATE,
    Permission.TEMPLATE_VIEW,
    Permission.TEMPLATE_EDIT,
    Permission.TEMPLATE_USE,
    Permission.STATISTICS_VIEW,
    Permission.STATISTICS_EXPORT,
    Permission.USER_MANAGE,
    Permission.ROLE_MANAGE,
    Permission.AUDIT_LOG_VIEW,
    Permission.UNAUTHORIZED_VIEW,
  ],
};

export const roleLabels: Record<UserRole, string> = {
  [UserRole.AUDITOR]: '审计员',
  [UserRole.BUSINESS_OWNER]: '业务负责人',
  [UserRole.COMPLIANCE_OFFICER]: '合规官',
  [UserRole.MANAGEMENT]: '管理层',
  [UserRole.ADMIN]: '系统管理员',
};

export const roleColors: Record<UserRole, string> = {
  [UserRole.AUDITOR]: 'blue',
  [UserRole.BUSINESS_OWNER]: 'green',
  [UserRole.COMPLIANCE_OFFICER]: 'purple',
  [UserRole.MANAGEMENT]: 'gold',
  [UserRole.ADMIN]: 'red',
};

export const permissionLabels: Record<Permission, string> = {
  [Permission.TASK_CREATE]: '创建任务',
  [Permission.TASK_ASSIGN]: '分配任务',
  [Permission.TASK_VIEW]: '查看任务',
  [Permission.TASK_EDIT]: '编辑任务',
  [Permission.TASK_BATCH_UPDATE]: '任务批量更新',
  [Permission.TASK_DELETE]: '删除任务',
  [Permission.EVIDENCE_CREATE]: '证据创建',
  [Permission.EVIDENCE_UPLOAD]: '上传证据',
  [Permission.EVIDENCE_VIEW]: '查看证据',
  [Permission.EVIDENCE_EDIT]: '编辑证据',
  [Permission.EVIDENCE_SUBMIT]: '证据提交',
  [Permission.EVIDENCE_DELETE]: '删除证据',
  [Permission.REVIEW_CONDUCT]: '执行复核',
  [Permission.REVIEW_APPROVE]: '复核通过',
  [Permission.REVIEW_REJECT]: '复核拒绝',
  [Permission.REVIEW_VIEW]: '复核查看',
  [Permission.CHECKLIST_CREATE]: '检查清单创建',
  [Permission.CHECKLIST_VIEW]: '查看检查清单',
  [Permission.CHECKLIST_EDIT]: '检查清单编辑',
  [Permission.CHECKLIST_EXECUTE]: '检查清单执行',
  [Permission.SAMPLING_CREATE]: '抽样创建',
  [Permission.SAMPLING_VIEW]: '查看抽样',
  [Permission.SAMPLING_EDIT]: '编辑抽样',
  [Permission.SAMPLING_APPROVE]: '抽样审批',
  [Permission.TEMPLATE_CREATE]: '模板创建',
  [Permission.TEMPLATE_VIEW]: '模板查看',
  [Permission.TEMPLATE_EDIT]: '模板编辑',
  [Permission.TEMPLATE_USE]: '模板使用',
  [Permission.STATISTICS_VIEW]: '查看统计',
  [Permission.STATISTICS_EXPORT]: '统计导出',
  [Permission.USER_MANAGE]: '用户管理',
  [Permission.ROLE_MANAGE]: '角色管理',
  [Permission.AUDIT_LOG_VIEW]: '查看操作日志',
  [Permission.UNAUTHORIZED_VIEW]: '越权记录查看',
};
