declare module 'cc' {
    export const _decorator: any;
    export type Component = any;
    export const Component: any;
    export type Node = any;
    export const Node: any;
    export type Scene = any;
    export const Scene: any;
    export type Label = any;
    export const Label: any;
    export type Sprite = any;
    export const Sprite: any;
    export type Button = any;
    export const Button: any;
    export type EditBox = any;
    export const EditBox: any;
    export type ScrollView = any;
    export const ScrollView: any;
    export type View = any;
    export const View: any;
    export type Color = any;
    export const Color: any;
    export type UITransform = any;
    export const UITransform: any;
    export type Vec3 = any;
    export const Vec3: any;
    export type Vec2 = any;
    export const Vec2: any;
    export type Vec4 = any;
    export const Vec4: any;
    export type Quat = any;
    export const Quat: any;
    export type Size = any;
    export const Size: any;
    export type UIOpacity = any;
    export const UIOpacity: any;
    export type ProgressBar = any;
    export const ProgressBar: any;
    export type Mask = any;
    export const Mask: any;
    export type Layout = any;
    export const Layout: any;
    export const director: any;
    export const game: any;
    export const find: any;
    export type Prefab = any;
    export const Prefab: any;
    export const instantiate: any;
    export type Widget = any;
    export const Widget: any;
    export type Graphics = any;
    export const Graphics: any;
    export const tween: any;
    export type EventTouch = any;
    export const EventTouch: any;
    export const Toggle: any;
    export type Toggle = any;
    export type TiledMap = any;
    export const TiledMap: any;
    export type TiledTile = any;
    export const TiledTile: any;
    export type TiledLayer = any;
    export const TiledLayer: any;
}
