# Generated by Django 5.1.15 on 2026-06-18 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('missing_type', models.CharField(choices=[('buyer_id', '买方身份证'), ('seller_id', '卖方身份证'), ('license', '行驶证'), ('registration', '登记证'), ('contract', '合同'), ('finance', '金融资料'), ('other', '其他')], max_length=30, verbose_name='缺失类型')),
                ('urgency', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='紧急程度')),
                ('status', models.CharField(choices=[('open', '待处理'), ('reminded', '已催办'), ('escalated', '已升级'), ('resolved', '已补齐'), ('closed', '已关闭')], default='open', max_length=15, verbose_name='状态')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
            ],
            options={
                'verbose_name': '异常项',
                'verbose_name_plural': '异常项',
            },
        ),
        migrations.CreateModel(
            name='ExceptionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('exception_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='transfertracker.exceptionitem', verbose_name='异常项')),
            ],
            options={
                'verbose_name': '异常处理记录',
                'verbose_name_plural': '异常处理记录',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file', models.FileField(upload_to='attachments/', verbose_name='文件')),
                ('file_size', models.IntegerField(verbose_name='文件大小(bytes)')),
                ('related_obj_id', models.UUIDField(verbose_name='关联对象ID')),
                ('related_obj_type', models.CharField(choices=[('finance', '金融资料'), ('vehicle_license', '行驶证'), ('vehicle_registration', '登记证')], max_length=50, verbose_name='关联对象类型')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '文件附件',
                'verbose_name_plural': '文件附件',
                'indexes': [models.Index(fields=['related_obj_type', 'related_obj_id'], name='idx_file_related')],
            },
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_no', models.CharField(max_length=50, unique=True, verbose_name='合同编号')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('review', '待复核'), ('completed', '已完成'), ('exception', '异常')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('buyer_name', models.CharField(max_length=100, verbose_name='买方姓名')),
                ('buyer_id_no', models.CharField(max_length=30, verbose_name='买方身份证号')),
                ('seller_name', models.CharField(max_length=100, verbose_name='卖方姓名')),
                ('seller_id_no', models.CharField(max_length=30, verbose_name='卖方身份证号')),
                ('transfer_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='过户税费')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('review_note', models.TextField(blank=True, verbose_name='复核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_records', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
            options={
                'verbose_name': '过户记录',
                'verbose_name_plural': '过户记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='报价金额')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('quoted_at', models.DateTimeField(auto_now_add=True, verbose_name='报价时间')),
                ('quoted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='报价人')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='transfertracker.transferrecord', verbose_name='过户记录')),
            ],
            options={
                'verbose_name': '报价记录',
                'verbose_name_plural': '报价记录',
                'ordering': ['-quoted_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_scheme', models.CharField(blank=True, max_length=100, verbose_name='贷款方案')),
                ('down_payment_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='首付比例')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='月供金额')),
                ('months', models.IntegerField(blank=True, null=True, verbose_name='贷款月数')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='金融机构')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_doc', to='transfertracker.transferrecord', verbose_name='过户记录')),
            ],
            options={
                'verbose_name': '金融资料',
                'verbose_name_plural': '金融资料',
            },
        ),
        migrations.AddField(
            model_name='exceptionitem',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_items', to='transfertracker.transferrecord', verbose_name='过户记录'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('specialist', '过户专员'), ('manager', '门店经理'), ('finance', '财务人员')], default='specialist', max_length=20, verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
            },
        ),
        migrations.CreateModel(
            name='VehicleProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('model', models.CharField(max_length=100, verbose_name='型号')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN码')),
                ('mileage', models.IntegerField(blank=True, null=True, verbose_name='里程数(km)')),
                ('condition_grade', models.CharField(blank=True, choices=[('A', 'A-优秀'), ('B', 'B-良好'), ('C', 'C-一般'), ('D', 'D-较差')], max_length=1, null=True, verbose_name='车况评级')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='初次登记日期')),
                ('source_channel', models.CharField(blank=True, max_length=50, verbose_name='来源渠道')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_profile', to='transfertracker.transferrecord', verbose_name='过户记录')),
            ],
            options={
                'verbose_name': '车辆档案',
                'verbose_name_plural': '车辆档案',
            },
        ),
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50, verbose_name='标签名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tags', to='transfertracker.transferrecord', verbose_name='过户记录')),
            ],
            options={
                'verbose_name': '复盘标签',
                'verbose_name_plural': '复盘标签',
                'indexes': [models.Index(fields=['tag_name'], name='idx_tag_name')],
                'unique_together': {('record', 'tag_name')},
            },
        ),
        migrations.AddIndex(
            model_name='exceptionitem',
            index=models.Index(fields=['status'], name='idx_exception_status'),
        ),
        migrations.AddIndex(
            model_name='exceptionitem',
            index=models.Index(fields=['urgency'], name='idx_exception_urgency'),
        ),
    ]
