# Generated by Django 4.2.7 on 2026-06-18 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestDriveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_no', models.CharField(max_length=50, unique=True, verbose_name='试驾单号')),
                ('customer_name', models.CharField(max_length=50, verbose_name='客户姓名')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='客户电话')),
                ('customer_id_card', models.CharField(blank=True, max_length=18, verbose_name='客户身份证')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='驾驶证号')),
                ('status', models.CharField(choices=[('scheduled', '已预约'), ('in_progress', '试驾中'), ('completed', '已完成'), ('cancelled', '已取消')], default='scheduled', max_length=20, verbose_name='试驾状态')),
                ('scheduled_at', models.DateTimeField(verbose_name='预约时间')),
                ('start_mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='出发里程')),
                ('end_mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='返回里程')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='出发时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='返回时间')),
                ('route', models.CharField(blank=True, max_length=500, verbose_name='试驾路线')),
                ('feedback', models.TextField(blank=True, verbose_name='客户反馈')),
                ('brake_feeling', models.CharField(blank=True, max_length=100, verbose_name='制动感受')),
                ('shift_feeling', models.CharField(blank=True, max_length=100, verbose_name='换挡感受')),
                ('ride_comfort', models.CharField(blank=True, max_length=100, verbose_name='乘坐舒适性')),
                ('noise_level', models.CharField(blank=True, max_length=100, verbose_name='噪音水平')),
                ('handling', models.CharField(blank=True, max_length=100, verbose_name='操控性能')),
                ('abnormal_noise', models.TextField(blank=True, verbose_name='异常响声')),
                ('other_issues', models.TextField(blank=True, verbose_name='其他问题')),
                ('purchase_intent', models.CharField(blank=True, choices=[('high', '高意向'), ('medium', '中意向'), ('low', '低意向'), ('none', '无意向')], max_length=20, verbose_name='购车意向')),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='客户期望价(元)')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('verified', models.BooleanField(default=False, verbose_name='是否已复核')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '试驾记录',
                'verbose_name_plural': '试驾记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
