# Generated by Django 4.2.7 on 2026-06-18 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
        ('testdrives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdriverecord',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testdrives', to=settings.AUTH_USER_MODEL, verbose_name='负责销售'),
        ),
        migrations.AddField(
            model_name='testdriverecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testdrive_records', to='vehicles.vehicle', verbose_name='车源'),
        ),
        migrations.AddField(
            model_name='testdriverecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_testdrives', to=settings.AUTH_USER_MODEL, verbose_name='复核人'),
        ),
    ]
