import type { LevelConfig } from './types';

const levelConfigs: LevelConfig[] = [
  {
    id: 'lv1',
    name: '晨间开园',
    description: '处理早间第一批游客的票务核销，练习基础验证流程',
    timeLimitSec: 120,
    difficulty: 1,
    targetScore: 60,
    performanceSlots: [
      { id: 's1', name: '民俗舞', time: '09:00', capacity: 200, basePrice: 80, category: 'dance' },
      { id: 's2', name: '山歌对唱', time: '10:00', capacity: 150, basePrice: 60, category: 'music' },
      { id: 's3', name: '杂技秀', time: '11:00', capacity: 300, basePrice: 120, category: 'acrobatics' },
    ],
    ticketRules: [
      { id: 'tr1', name: '成人票', color: 0x4fc3f7, discountRate: 1.0, validSlots: ['s1', 's2', 's3'], maxPerOrder: 6, requiresSponsor: false },
      { id: 'tr2', name: '儿童票', color: 0x81c784, discountRate: 0.5, validSlots: ['s1', 's2'], maxPerOrder: 4, requiresSponsor: false },
      { id: 'tr3', name: 'VIP票', color: 0xffd54f, discountRate: 1.2, validSlots: ['s1', 's2', 's3'], maxPerOrder: 2, requiresSponsor: false },
    ],
    sponsors: [
      { id: 'sp1', name: '百味斋', tier: 'silver', preferredSlots: ['s1'], budget: 5000, requiresVerification: true },
      { id: 'sp2', name: '山泉饮品', tier: 'bronze', preferredSlots: ['s2'], budget: 3000, requiresVerification: false },
    ],
    verificationRecords: [
      { id: 'v1', ticketRuleId: 'tr1', slotId: 's1', isValid: true },
      { id: 'v2', ticketRuleId: 'tr2', slotId: 's3', isValid: false, reason: '儿童票不可用于杂技秀' },
      { id: 'v3', ticketRuleId: 'tr3', slotId: 's1', isValid: true },
      { id: 'v4', ticketRuleId: 'tr1', slotId: 's2', isValid: true },
      { id: 'v5', ticketRuleId: 'tr2', slotId: 's2', isValid: true },
    ],
  },
  {
    id: 'lv2',
    name: '午间高峰',
    description: '午间客流高峰，更多演出场次与复杂票种规则',
    timeLimitSec: 100,
    difficulty: 2,
    targetScore: 70,
    performanceSlots: [
      { id: 's1', name: '皮影戏', time: '12:00', capacity: 120, basePrice: 50, category: 'traditional' },
      { id: 's2', name: '川剧变脸', time: '13:00', capacity: 250, basePrice: 100, category: 'opera' },
      { id: 's3', name: '乐队演出', time: '14:00', capacity: 400, basePrice: 150, category: 'music' },
      { id: 's4', name: '灯光秀', time: '15:00', capacity: 500, basePrice: 80, category: 'visual' },
    ],
    ticketRules: [
      { id: 'tr1', name: '成人票', color: 0x4fc3f7, discountRate: 1.0, validSlots: ['s1', 's2', 's3', 's4'], maxPerOrder: 6, requiresSponsor: false },
      { id: 'tr2', name: '儿童票', color: 0x81c784, discountRate: 0.5, validSlots: ['s1', 's2'], maxPerOrder: 4, requiresSponsor: false },
      { id: 'tr3', name: 'VIP票', color: 0xffd54f, discountRate: 1.2, validSlots: ['s1', 's2', 's3', 's4'], maxPerOrder: 2, requiresSponsor: false },
      { id: 'tr4', name: '赞助商票', color: 0xf06292, discountRate: 0.0, validSlots: ['s2', 's3'], maxPerOrder: 10, requiresSponsor: true },
      { id: 'tr5', name: '老年票', color: 0xba68c8, discountRate: 0.3, validSlots: ['s1', 's4'], maxPerOrder: 2, requiresSponsor: false },
    ],
    sponsors: [
      { id: 'sp1', name: '龙腾集团', tier: 'gold', preferredSlots: ['s2', 's3'], budget: 15000, requiresVerification: true },
      { id: 'sp2', name: '百味斋', tier: 'silver', preferredSlots: ['s1'], budget: 5000, requiresVerification: true },
      { id: 'sp3', name: '山泉饮品', tier: 'bronze', preferredSlots: ['s4'], budget: 3000, requiresVerification: false },
    ],
    verificationRecords: [
      { id: 'v1', ticketRuleId: 'tr1', slotId: 's1', isValid: true },
      { id: 'v2', ticketRuleId: 'tr2', slotId: 's3', isValid: false, reason: '儿童票不可用于乐队演出' },
      { id: 'v3', ticketRuleId: 'tr4', slotId: 's2', isValid: true },
      { id: 'v4', ticketRuleId: 'tr5', slotId: 's3', isValid: false, reason: '老年票不可用于乐队演出' },
      { id: 'v5', ticketRuleId: 'tr3', slotId: 's4', isValid: true },
      { id: 'v6', ticketRuleId: 'tr4', slotId: 's1', isValid: false, reason: '赞助商票不可用于皮影戏' },
      { id: 'v7', ticketRuleId: 'tr1', slotId: 's2', isValid: true },
      { id: 'v8', ticketRuleId: 'tr5', slotId: 's4', isValid: true },
    ],
  },
  {
    id: 'lv3',
    name: '夜间盛典',
    description: '夜间大型活动，赞助商密集，票种交叉验证，考验综合判断',
    timeLimitSec: 90,
    difficulty: 3,
    targetScore: 80,
    performanceSlots: [
      { id: 's1', name: '焰火秀', time: '19:00', capacity: 800, basePrice: 200, category: 'visual' },
      { id: 's2', name: '民族歌舞', time: '20:00', capacity: 350, basePrice: 120, category: 'dance' },
      { id: 's3', name: '非遗展演', time: '20:30', capacity: 200, basePrice: 90, category: 'traditional' },
      { id: 's4', name: '摇滚夜场', time: '21:00', capacity: 600, basePrice: 180, category: 'music' },
      { id: 's5', name: '灯会巡游', time: '22:00', capacity: 1000, basePrice: 50, category: 'visual' },
    ],
    ticketRules: [
      { id: 'tr1', name: '成人票', color: 0x4fc3f7, discountRate: 1.0, validSlots: ['s1', 's2', 's3', 's4', 's5'], maxPerOrder: 8, requiresSponsor: false },
      { id: 'tr2', name: '儿童票', color: 0x81c784, discountRate: 0.5, validSlots: ['s2', 's3', 's5'], maxPerOrder: 4, requiresSponsor: false },
      { id: 'tr3', name: 'VIP票', color: 0xffd54f, discountRate: 1.2, validSlots: ['s1', 's2', 's4'], maxPerOrder: 4, requiresSponsor: false },
      { id: 'tr4', name: '赞助商票', color: 0xf06292, discountRate: 0.0, validSlots: ['s1', 's2', 's4'], maxPerOrder: 20, requiresSponsor: true },
      { id: 'tr5', name: '老年票', color: 0xba68c8, discountRate: 0.3, validSlots: ['s2', 's3', 's5'], maxPerOrder: 2, requiresSponsor: false },
      { id: 'tr6', name: '夜场套票', color: 0x4db6ac, discountRate: 0.85, validSlots: ['s1', 's4', 's5'], maxPerOrder: 4, requiresSponsor: false },
    ],
    sponsors: [
      { id: 'sp1', name: '龙腾集团', tier: 'gold', preferredSlots: ['s1', 's4'], budget: 20000, requiresVerification: true },
      { id: 'sp2', name: '星辰科技', tier: 'gold', preferredSlots: ['s4'], budget: 18000, requiresVerification: true },
      { id: 'sp3', name: '百味斋', tier: 'silver', preferredSlots: ['s2', 's3'], budget: 8000, requiresVerification: true },
      { id: 'sp4', name: '山泉饮品', tier: 'bronze', preferredSlots: ['s5'], budget: 4000, requiresVerification: false },
    ],
    verificationRecords: [
      { id: 'v1', ticketRuleId: 'tr1', slotId: 's1', isValid: true },
      { id: 'v2', ticketRuleId: 'tr2', slotId: 's4', isValid: false, reason: '儿童票不可用于摇滚夜场' },
      { id: 'v3', ticketRuleId: 'tr4', slotId: 's1', isValid: true },
      { id: 'v4', ticketRuleId: 'tr5', slotId: 's4', isValid: false, reason: '老年票不可用于摇滚夜场' },
      { id: 'v5', ticketRuleId: 'tr6', slotId: 's5', isValid: true },
      { id: 'v6', ticketRuleId: 'tr3', slotId: 's1', isValid: true },
      { id: 'v7', ticketRuleId: 'tr4', slotId: 's3', isValid: false, reason: '赞助商票不可用于非遗展演' },
      { id: 'v8', ticketRuleId: 'tr2', slotId: 's2', isValid: true },
      { id: 'v9', ticketRuleId: 'tr6', slotId: 's2', isValid: false, reason: '夜场套票不可用于民族歌舞' },
      { id: 'v10', ticketRuleId: 'tr5', slotId: 's5', isValid: true },
      { id: 'v11', ticketRuleId: 'tr1', slotId: 's4', isValid: true },
      { id: 'v12', ticketRuleId: 'tr3', slotId: 's5', isValid: false, reason: 'VIP票不可用于灯会巡游' },
    ],
  },
  {
    id: 'lv4',
    name: '节假日专场',
    description: '国庆黄金周，多场大型演出并行，赞助商权益复杂，高强度训练',
    timeLimitSec: 80,
    difficulty: 4,
    targetScore: 90,
    performanceSlots: [
      { id: 's1', name: '开国大典', time: '10:00', capacity: 1000, basePrice: 300, category: 'special' },
      { id: 's2', name: '花车巡游', time: '14:00', capacity: 2000, basePrice: 150, category: 'parade' },
      { id: 's3', name: '烟花晚会', time: '20:00', capacity: 3000, basePrice: 400, category: 'visual' },
      { id: 's4', name: '非遗市集', time: '11:00', capacity: 500, basePrice: 80, category: 'traditional' },
      { id: 's5', name: '音乐节', time: '16:00', capacity: 1500, basePrice: 250, category: 'music' },
      { id: 's6', name: '激光秀', time: '22:00', capacity: 2500, basePrice: 180, category: 'visual' },
    ],
    ticketRules: [
      { id: 'tr1', name: '成人票', color: 0x4fc3f7, discountRate: 1.0, validSlots: ['s1', 's2', 's3', 's4', 's5', 's6'], maxPerOrder: 10, requiresSponsor: false },
      { id: 'tr2', name: '儿童票', color: 0x81c784, discountRate: 0.5, validSlots: ['s2', 's4', 's6'], maxPerOrder: 5, requiresSponsor: false },
      { id: 'tr3', name: 'VIP票', color: 0xffd54f, discountRate: 1.5, validSlots: ['s1', 's3', 's5'], maxPerOrder: 4, requiresSponsor: false },
      { id: 'tr4', name: '赞助商票', color: 0xf06292, discountRate: 0.0, validSlots: ['s1', 's3', 's5'], maxPerOrder: 30, requiresSponsor: true },
      { id: 'tr5', name: '老年票', color: 0xba68c8, discountRate: 0.3, validSlots: ['s2', 's4', 's6'], maxPerOrder: 2, requiresSponsor: false },
      { id: 'tr6', name: '家庭套票', color: 0x4db6ac, discountRate: 0.75, validSlots: ['s2', 's4', 's6'], maxPerOrder: 8, requiresSponsor: false },
      { id: 'tr7', name: '通票', color: 0xffb74d, discountRate: 0.9, validSlots: ['s1', 's2', 's3', 's4', 's5', 's6'], maxPerOrder: 6, requiresSponsor: false },
    ],
    sponsors: [
      { id: 'sp1', name: '国家旅游局', tier: 'gold', preferredSlots: ['s1', 's3'], budget: 50000, requiresVerification: true },
      { id: 'sp2', name: '龙腾集团', tier: 'gold', preferredSlots: ['s3', 's5'], budget: 30000, requiresVerification: true },
      { id: 'sp3', name: '星辰科技', tier: 'gold', preferredSlots: ['s5'], budget: 25000, requiresVerification: true },
      { id: 'sp4', name: '百味斋', tier: 'silver', preferredSlots: ['s2', 's4'], budget: 15000, requiresVerification: true },
      { id: 'sp5', name: '山泉饮品', tier: 'silver', preferredSlots: ['s4', 's6'], budget: 12000, requiresVerification: true },
      { id: 'sp6', name: '本地文旅', tier: 'bronze', preferredSlots: ['s2'], budget: 8000, requiresVerification: false },
    ],
    verificationRecords: [
      { id: 'v1', ticketRuleId: 'tr1', slotId: 's1', isValid: true },
      { id: 'v2', ticketRuleId: 'tr2', slotId: 's1', isValid: false, reason: '儿童票不可用于开国大典' },
      { id: 'v3', ticketRuleId: 'tr4', slotId: 's3', isValid: true },
      { id: 'v4', ticketRuleId: 'tr5', slotId: 's5', isValid: false, reason: '老年票不可用于音乐节' },
      { id: 'v5', ticketRuleId: 'tr6', slotId: 's2', isValid: true },
      { id: 'v6', ticketRuleId: 'tr3', slotId: 's3', isValid: true },
      { id: 'v7', ticketRuleId: 'tr4', slotId: 's4', isValid: false, reason: '赞助商票不可用于非遗市集' },
      { id: 'v8', ticketRuleId: 'tr2', slotId: 's6', isValid: true },
      { id: 'v9', ticketRuleId: 'tr7', slotId: 's5', isValid: true },
      { id: 'v10', ticketRuleId: 'tr5', slotId: 's4', isValid: true },
      { id: 'v11', ticketRuleId: 'tr1', slotId: 's3', isValid: true },
      { id: 'v12', ticketRuleId: 'tr3', slotId: 's6', isValid: false, reason: 'VIP票不可用于激光秀' },
      { id: 'v13', ticketRuleId: 'tr6', slotId: 's1', isValid: false, reason: '家庭套票不可用于开国大典' },
      { id: 'v14', ticketRuleId: 'tr4', slotId: 's5', isValid: true },
      { id: 'v15', ticketRuleId: 'tr7', slotId: 's2', isValid: true },
    ],
  },
  {
    id: 'lv5',
    name: '年终盛典',
    description: '年度收官大作，全景区联动，考验极限运营能力',
    timeLimitSec: 70,
    difficulty: 5,
    targetScore: 100,
    performanceSlots: [
      { id: 's1', name: '跨年演唱会', time: '20:00', capacity: 5000, basePrice: 500, category: 'music' },
      { id: 's2', name: '灯光艺术节', time: '18:00', capacity: 3000, basePrice: 200, category: 'visual' },
      { id: 's3', name: '非遗传承展', time: '14:00', capacity: 800, basePrice: 150, category: 'traditional' },
      { id: 's4', name: '美食嘉年华', time: '16:00', capacity: 2000, basePrice: 100, category: 'food' },
      { id: 's5', name: '冰雪大世界', time: '10:00', capacity: 4000, basePrice: 280, category: 'special' },
      { id: 's6', name: '跨年烟花', time: '23:59', capacity: 8000, basePrice: 600, category: 'visual' },
      { id: 's7', name: '沉浸式剧场', time: '21:00', capacity: 300, basePrice: 350, category: 'theater' },
    ],
    ticketRules: [
      { id: 'tr1', name: '成人票', color: 0x4fc3f7, discountRate: 1.0, validSlots: ['s1', 's2', 's3', 's4', 's5', 's6', 's7'], maxPerOrder: 12, requiresSponsor: false },
      { id: 'tr2', name: '儿童票', color: 0x81c784, discountRate: 0.5, validSlots: ['s2', 's3', 's4', 's5'], maxPerOrder: 6, requiresSponsor: false },
      { id: 'tr3', name: 'VIP票', color: 0xffd54f, discountRate: 1.5, validSlots: ['s1', 's6', 's7'], maxPerOrder: 6, requiresSponsor: false },
      { id: 'tr4', name: '赞助商票', color: 0xf06292, discountRate: 0.0, validSlots: ['s1', 's6', 's7'], maxPerOrder: 50, requiresSponsor: true },
      { id: 'tr5', name: '老年票', color: 0xba68c8, discountRate: 0.3, validSlots: ['s2', 's3', 's5'], maxPerOrder: 3, requiresSponsor: false },
      { id: 'tr6', name: '家庭套票', color: 0x4db6ac, discountRate: 0.7, validSlots: ['s2', 's4', 's5'], maxPerOrder: 10, requiresSponsor: false },
      { id: 'tr7', name: '通票', color: 0xffb74d, discountRate: 0.85, validSlots: ['s1', 's2', 's3', 's4', 's5', 's6', 's7'], maxPerOrder: 8, requiresSponsor: false },
      { id: 'tr8', name: '学生票', color: 0x7986cb, discountRate: 0.4, validSlots: ['s2', 's3', 's5'], maxPerOrder: 4, requiresSponsor: false },
    ],
    sponsors: [
      { id: 'sp1', name: '央视春晚', tier: 'gold', preferredSlots: ['s1', 's6'], budget: 100000, requiresVerification: true },
      { id: 'sp2', name: '国家旅游局', tier: 'gold', preferredSlots: ['s6'], budget: 80000, requiresVerification: true },
      { id: 'sp3', name: '龙腾集团', tier: 'gold', preferredSlots: ['s1', 's7'], budget: 60000, requiresVerification: true },
      { id: 'sp4', name: '星辰科技', tier: 'gold', preferredSlots: ['s1'], budget: 50000, requiresVerification: true },
      { id: 'sp5', name: '百味斋', tier: 'silver', preferredSlots: ['s4', 's3'], budget: 25000, requiresVerification: true },
      { id: 'sp6', name: '山泉饮品', tier: 'silver', preferredSlots: ['s4', 's5'], budget: 20000, requiresVerification: true },
      { id: 'sp7', name: '冰雪集团', tier: 'silver', preferredSlots: ['s5'], budget: 30000, requiresVerification: true },
      { id: 'sp8', name: '本地文旅', tier: 'bronze', preferredSlots: ['s2'], budget: 10000, requiresVerification: false },
    ],
    verificationRecords: [
      { id: 'v1', ticketRuleId: 'tr1', slotId: 's1', isValid: true },
      { id: 'v2', ticketRuleId: 'tr2', slotId: 's1', isValid: false, reason: '儿童票不可用于跨年演唱会' },
      { id: 'v3', ticketRuleId: 'tr4', slotId: 's6', isValid: true },
      { id: 'v4', ticketRuleId: 'tr5', slotId: 's1', isValid: false, reason: '老年票不可用于跨年演唱会' },
      { id: 'v5', ticketRuleId: 'tr6', slotId: 's5', isValid: true },
      { id: 'v6', ticketRuleId: 'tr3', slotId: 's7', isValid: true },
      { id: 'v7', ticketRuleId: 'tr4', slotId: 's3', isValid: false, reason: '赞助商票不可用于非遗传承展' },
      { id: 'v8', ticketRuleId: 'tr8', slotId: 's3', isValid: true },
      { id: 'v9', ticketRuleId: 'tr7', slotId: 's6', isValid: true },
      { id: 'v10', ticketRuleId: 'tr5', slotId: 's5', isValid: true },
      { id: 'v11', ticketRuleId: 'tr1', slotId: 's6', isValid: true },
      { id: 'v12', ticketRuleId: 'tr3', slotId: 's4', isValid: false, reason: 'VIP票不可用于美食嘉年华' },
      { id: 'v13', ticketRuleId: 'tr6', slotId: 's1', isValid: false, reason: '家庭套票不可用于跨年演唱会' },
      { id: 'v14', ticketRuleId: 'tr4', slotId: 's7', isValid: true },
      { id: 'v15', ticketRuleId: 'tr8', slotId: 's7', isValid: false, reason: '学生票不可用于沉浸式剧场' },
      { id: 'v16', ticketRuleId: 'tr7', slotId: 's4', isValid: true },
      { id: 'v17', ticketRuleId: 'tr2', slotId: 's4', isValid: true },
      { id: 'v18', ticketRuleId: 'tr5', slotId: 's2', isValid: true },
    ],
  },
];

export default levelConfigs;
