development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  database: mp0164_development
  username: yaoleyxing

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  database: mp0164_test
  username: yaoleyxing

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  database: mp0164_production
  username: mp0164
  password: <%= ENV["MP0164_DATABASE_PASSWORD"] %>
