# Generated by Django 4.2.7 on 2026-06-18 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='车架号/VIN')),
                ('plate_number', models.CharField(blank=True, max_length=20, verbose_name='车牌号')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('model', models.CharField(max_length=100, verbose_name='车型')),
                ('year', models.IntegerField(verbose_name='年款')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='颜色')),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='公里数(km)')),
                ('displacement', models.CharField(blank=True, max_length=50, verbose_name='排量')),
                ('fuel_type', models.CharField(choices=[('gasoline', '汽油'), ('diesel', '柴油'), ('hybrid', '混动'), ('electric', '纯电'), ('other', '其他')], default='gasoline', max_length=20, verbose_name='燃料类型')),
                ('transmission', models.CharField(choices=[('manual', '手动'), ('automatic', '自动'), ('cvt', 'CVT'), ('dual_clutch', '双离合')], default='automatic', max_length=20, verbose_name='变速箱')),
                ('first_register_date', models.DateField(blank=True, null=True, verbose_name='首次上牌日期')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='收车价(元)')),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='期望售价(元)')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实际售价(元)')),
                ('status', models.CharField(choices=[('pending_evaluation', '待评估'), ('pending_inspection', '待检测'), ('pending_preparation', '待整备'), ('pending_testdrive', '待试驾'), ('pending_review', '待审核'), ('listed', '已上架'), ('sold', '已售出'), ('off_shelf', '已下架'), ('rejected', '审核驳回')], default='pending_evaluation', max_length=30, verbose_name='车源状态')),
                ('review_status', models.CharField(choices=[('pending', '待复核'), ('pass', '复核通过'), ('reject', '资料缺失'), ('supplemented', '已补充待再审')], default='pending', max_length=20, verbose_name='复核状态')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='车源来源')),
                ('owner_name', models.CharField(blank=True, max_length=50, verbose_name='原车主姓名')),
                ('owner_phone', models.CharField(blank=True, max_length=20, verbose_name='原车主电话')),
                ('description', models.TextField(blank=True, verbose_name='车辆描述')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('listed_at', models.DateTimeField(blank=True, null=True, verbose_name='上架时间')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='售出时间')),
                ('appraiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraised_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='评估师')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='负责销售')),
            ],
            options={
                'verbose_name': '车源/车辆档案',
                'verbose_name_plural': '车源/车辆档案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('pending_evaluation', '待评估'), ('pending_inspection', '待检测'), ('pending_preparation', '待整备'), ('pending_testdrive', '待试驾'), ('pending_review', '待审核'), ('listed', '已上架'), ('sold', '已售出'), ('off_shelf', '已下架'), ('rejected', '审核驳回')], max_length=30, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('pending_evaluation', '待评估'), ('pending_inspection', '待检测'), ('pending_preparation', '待整备'), ('pending_testdrive', '待试驾'), ('pending_review', '待审核'), ('listed', '已上架'), ('sold', '已售出'), ('off_shelf', '已下架'), ('rejected', '审核驳回')], max_length=30, verbose_name='新状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='vehicles.vehicle', verbose_name='车源')),
            ],
            options={
                'verbose_name': '状态变更日志',
                'verbose_name_plural': '状态变更日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待复核'), ('pass', '复核通过'), ('reject', '资料缺失'), ('supplemented', '已补充待再审')], max_length=20, verbose_name='复核结论')),
                ('comment', models.TextField(blank=True, verbose_name='复核意见')),
                ('missing_items', models.JSONField(blank=True, default=list, verbose_name='缺失材料列表')),
                ('conclusion', models.TextField(blank=True, verbose_name='关闭结论')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='vehicles.vehicle', verbose_name='车源')),
            ],
            options={
                'verbose_name': '复核记录',
                'verbose_name_plural': '复核记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
