# Generated by Django 4.2.7 on 2026-06-15 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待发放'), ('following', '待跟进'), ('reviewing', '待复核'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('distributed_at', models.DateTimeField(auto_now_add=True, verbose_name='发放时间')),
                ('risk_level', models.CharField(blank=True, choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=10, null=True, verbose_name='风险等级')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='materials.material', verbose_name='教材')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '发放记录',
                'verbose_name_plural': '发放记录',
                'db_table': 'distribution',
                'ordering': ['-distributed_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributions.distribution', verbose_name='发放记录')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '发放记录标签',
                'verbose_name_plural': '发放记录标签',
                'db_table': 'distribution_tags',
                'unique_together': {('distribution', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='distribution',
            name='tags',
            field=models.ManyToManyField(related_name='distributions', through='distributions.DistributionTag', to='materials.tag', verbose_name='标签'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['status'], name='idx_distribution_status'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['risk_level'], name='idx_distribution_risk'),
        ),
    ]
