# Generated by Django 4.2.7 on 2026-06-18 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(help_text='如: registration_cert, driving_license, insurance 等', max_length=50, verbose_name='证件/材料类型')),
                ('category', models.CharField(choices=[('vehicle_archive', '车辆档案'), ('inspection', '检测报告'), ('preparation', '整备资料'), ('testdrive', '试驾资料'), ('finance', '金融资料'), ('other', '其他')], default='vehicle_archive', max_length=30, verbose_name='资料类别')),
                ('source', models.CharField(choices=[('uploaded', '手动上传'), ('scanned', '扫描生成'), ('system', '系统生成'), ('imported', '外部导入')], default='uploaded', max_length=20, verbose_name='材料来源')),
                ('title', models.CharField(max_length=200, verbose_name='文件标题')),
                ('description', models.TextField(blank=True, verbose_name='描述说明')),
                ('file_path', models.CharField(max_length=500, verbose_name='MinIO 对象路径')),
                ('file_name', models.CharField(max_length=200, verbose_name='原始文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME类型')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已核验')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='核验时间')),
                ('verification_note', models.TextField(blank=True, verbose_name='核验备注')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('process_history', models.JSONField(blank=True, default=list, verbose_name='处理过程记录')),
                ('close_conclusion', models.TextField(blank=True, verbose_name='关闭结论')),
                ('is_closed', models.BooleanField(default=False, verbose_name='是否关闭')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '车辆附件文档',
                'verbose_name_plural': '车辆附件文档',
                'ordering': ['-created_at'],
            },
        ),
    ]
