export const CALIBER_NOTES: Record<string, Record<string, string>> = {
  HEARING_SUMMARY: {
    hearingNo: '开庭编号：系统自动生成的唯一标识符，格式为 HT-YYYYMMDD-NNNN',
    caseNo: '所内案号：律师事务所内部登记的案件编号',
    courtCaseNo: '法院案号：法院立案时分配的案件编号',
    caseTitle: '案件名称：案件的标题或简称',
    courtName: '法院名称：受理案件的法院全称',
    courtRoom: '法庭：具体开庭地点',
    presidingJudge: '审判长：主审法官姓名',
    startTime: '开庭开始时间：实际开庭的起始时间，格式为 YYYY-MM-DD HH:mm',
    endTime: '开庭结束时间：实际开庭的结束时间，格式为 YYYY-MM-DD HH:mm',
    duration: '开庭时长(分钟)：实际开庭时长，计算方式为结束时间减去开始时间',
    hearingType: '开庭类型：包括开庭/听证/调解/宣判/谈话/质证等',
    status: '开庭状态：已排期/已确认/进行中/已完成/已改期/已取消/延期',
    isImportant: '重要标记：是否标记为重要开庭，默认否',
    priority: '优先级：1-10的数字，数值越大优先级越高，默认5',
    assignedLawyers: '指派律师：分配参与本次开庭的所有律师姓名，用顿号分隔',
    attendees: '出庭人员：实际到场的人员姓名，用顿号分隔',
    creator: '创建人：创建该开庭记录的用户姓名',
    createdAt: '创建时间：开庭记录创建的时间',
  },
  ATTENDANCE_STATS: {
    hearingNo: '开庭编号：关联的开庭编号',
    hearingTime: '开庭时间：关联开庭的开始时间',
    personName: '人员姓名：签到人的姓名',
    attendeeType: '人员类型：律师/客户/法官/其他工作人员',
    plannedRole: '计划角色：该人员在开庭中计划扮演的角色',
    status: '签到状态：未到场/已到场/迟到/缺席/请假/早退',
    checkInTime: '签到时间：实际签到时间，未签到则为空',
    checkOutTime: '签退时间：实际签退时间，未签退则为空',
    lateMinutes: '迟到(分钟)：超过开庭开始时间到场所用的分钟数',
    earlyLeaveMinutes: '早退(分钟)：早于开庭结束时间离开的分钟数',
    signType: '签到方式：现场签到/远程签到/请假',
    recordedBy: '记录人：登记该签到记录的人员姓名',
  },
  EXCEPTION_STATS: {
    exceptionNo: '异常单编号：系统自动生成的异常单编号，格式为 EX-YYYYMMDDHHmmss-NNNN',
    exceptionType: '异常类型：利益冲突/程序错误/错过期限/出勤问题/沟通失误/其他',
    title: '异常标题：对异常情况的简要概括',
    severity: '严重程度：低/中/高/严重',
    status: '处理状态：待处理/调查中/已解决/已关闭/已升级',
    caseNo: '关联案件：异常涉及的案件（如有）',
    hearingNo: '关联开庭：异常涉及的开庭（如有）',
    creator: '创建人：提交异常单的人员姓名',
    createdAt: '创建时间：异常单提交时间',
    resolver: '处理人：负责处理该异常的人员姓名',
    investigationResult: '调查结果：对异常原因的调查结论',
    handlingResult: '处理结果：采取的处理措施和结果说明',
    correctiveAction: '纠正措施：针对本次问题的整改措施',
    preventiveMeasure: '预防措施：防止类似问题再次发生的措施',
    estimatedLoss: '预估损失(元)：异常可能造成的经济损失预估值',
    actualLoss: '实际损失(元)：异常实际造成的经济损失',
    resolutionTime: '处理时长(小时)：从创建到解决所用的小时数',
  },
  CONFLICT_STATS: {
    hearingNo: '开庭编号：发生冲突的开庭编号',
    conflictType: '冲突类型：律师时间冲突/法庭冲突/客户利益冲突/法官时间冲突/案件对立冲突/其他',
    severity: '严重程度：低/中/高/严重',
    description: '冲突描述：对冲突情况的详细说明',
    partyAName: '涉及方A：冲突一方的名称',
    partyBName: '涉及方B：冲突另一方的名称',
    isResolved: '是否已解决：是否已采取措施解决该冲突',
    resolvedAt: '解决时间：冲突被标记为已解决的时间',
    resolvedBy: '解决人：处理该冲突的人员姓名',
    resolution: '解决方案：解决冲突所采取的具体措施',
    createdAt: '检测时间：冲突被系统检测或录入的时间',
  },
  REMINDER_SUMMARY: {
    reminderId: '提醒ID：提醒记录的唯一标识',
    hearingNo: '关联开庭：该提醒所属的开庭编号',
    reminderType: '提醒方式：邮件/短信/APP推送/微信/电话',
    title: '提醒标题：提醒消息的标题',
    content: '提醒内容：提醒消息的正文内容',
    scheduledTime: '计划发送时间：原定的提醒发送时间',
    sentAt: '实际发送时间：提醒实际被发送的时间',
    sendDelay: '发送延迟(分钟)：实际发送时间与计划发送时间的差值（分钟）',
    status: '发送状态：待发送/已发送/发送失败/已读/已确认',
    sender: '发送人：执行发送操作的人员姓名',
    recipientCount: '接收人数：该提醒的接收人总数',
    deliveredCount: '送达数：成功送达的接收人数',
    readCount: '已读数：标记为已读的接收人数',
    confirmedCount: '已确认数：标记为已确认的接收人数',
    failCount: '失败数：发送失败的接收人数',
    retryCount: '重试次数：该提醒被重新发送的次数',
    createdAt: '创建时间：提醒记录的创建时间',
  },
  CASE_SUMMARY: {
    caseNo: '所内案号：律师事务所内部登记的案件编号',
    courtCaseNo: '法院案号：法院立案时分配的案件编号',
    title: '案件名称：案件的全称',
    caseType: '案件类型：民事/刑事/行政/执行等',
    caseCategory: '案件分类：合同纠纷/劳动争议/知识产权等具体案由',
    status: '案件状态：待处理/进行中/已结案/暂停',
    clientName: '客户名称：委托方（客户）的名称',
    ownerClientNo: '客户编号：客户在系统中的唯一编号',
    lawyerInCharge: '主办律师：负责该案件的主办律师姓名',
    assistantInCharge: '律师助理：协助处理案件的律师助理姓名',
    courtLevel: '法院层级：一审/二审/再审/复核等',
    jurisdiction: '管辖法院：受理案件的法院名称',
    acceptanceDate: '受理日期：案件被受理的日期',
    deadlineDate: '截止日期：案件相关的重要期限截止日期',
    amountInvolved: '涉案金额(元)：案件涉及的金额数值',
    retentionFee: '律师费(元)：约定的律师费用',
    paymentStatus: '付费状态：客户律师费的缴纳状态',
    hearingCount: '开庭次数：该案件已排期的开庭总数',
    completedHearings: '已完成开庭：已标记为完成的开庭数量',
    pendingHearings: '待开庭：尚未进行的开庭数量',
    openExceptions: '待处理异常：关联的未关闭异常单数量',
    createdAt: '创建时间：案件记录创建时间',
  },
};

export const GENERAL_CALIBER = [
  {
    category: '时间字段口径',
    items: [
      { name: '日期格式', desc: '所有日期字段统一采用 ISO 8601 格式：YYYY-MM-DD HH:mm:ss' },
      { name: '时区', desc: '所有时间字段均以系统配置的时区（默认 Asia/Shanghai）为准' },
      { name: '统计区间', desc: '按创建时间或发生时间进行区间筛选，含起始时间，含结束时间 [start, end]' },
    ],
  },
  {
    category: '数据关联口径',
    items: [
      { name: '关联字段', desc: '跨表关联字段均采用 UUID 主键，展示时采用关联对象的名称或编号' },
      { name: '空值处理', desc: '未填写或不存在的关联字段以空字符串展示，不使用"无"、"--"等占位符' },
    ],
  },
  {
    category: '统计计算口径',
    items: [
      { name: '时长计算', desc: '时长（分钟/小时）均按结束时间减开始时间的差值计算，不考虑午休等中断' },
      { name: '金额字段', desc: '金额类字段保留 2 位小数，单位为人民币元，无千分位分隔' },
      { name: '状态统计', desc: '统计时以状态字段的最新值为准，不考虑历史中间状态' },
      { name: '计数口径', desc: '各类统计计数只统计有效记录，已逻辑删除的不计入' },
    ],
  },
  {
    category: '导出通用规则',
    items: [
      { name: '重复数据', desc: '按主表主键去重，确保每行数据的唯一性' },
      { name: '排序规则', desc: '默认按创建时间倒序（新数据在前），可根据业务需要调整' },
      { name: '数据范围', desc: '导出数据受筛选条件约束，无筛选时导出全部有权限访问的数据' },
      { name: '刷新频率', desc: '导出为快照形式，取执行导出瞬间的数据状态，与后续变更无关' },
    ],
  },
];
