/* eslint-disable */
// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes to this file as it will be overwritten
// on the next run of the TanStack Router CLI / Dev Server.
// You can safely delete this file if you want to regenerate it.

import { Route as rootRoute } from './routes/__root'
import { Route as loginImport } from './routes/login'
import { Route as indexImport } from './routes/index.lazy'
import { Route as contractsImport } from './routes/contracts.lazy'
import { Route as reconciliationImport } from './routes/reconciliation.lazy'
import { Route as billsImport } from './routes/bills.lazy'
import { Route as approvalImport } from './routes/approval.lazy'
import { Route as exceptionsImport } from './routes/exceptions.lazy'
import { Route as exportImport } from './routes/export.lazy'

const loginRoute = loginImport
const indexRoute = indexImport
const contractsRoute = contractsImport
const reconciliationRoute = reconciliationImport
const billsRoute = billsImport
const approvalRoute = approvalImport
const exceptionsRoute = exceptionsImport
const exportRoute = exportImport

export const routeTree = rootRoute.addChildren([
  loginRoute,
  indexRoute,
  contractsRoute,
  reconciliationRoute,
  billsRoute,
  approvalRoute,
  exceptionsRoute,
  exportRoute,
])

// Load any matching catch-all routes first for NotFoundError boundaries
const catchAllLoaders = {} as any
routeTree.addChildren([], catchAllLoaders)
