/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { createFileRoute } from '@tanstack/react-router';
import { Route as rootRouteImport } from './routes/__root';
import { Route as LayoutRouteImport } from './routes/_layout';
const LoginLazyRouteImport = createFileRoute('/login')();
const LayoutIndexLazyRouteImport = createFileRoute('/_layout/')();
const LayoutStatisticsLazyRouteImport = createFileRoute('/_layout/statistics')();
const LayoutAuditLogsLazyRouteImport = createFileRoute('/_layout/audit-logs')();
const LayoutOperationsSeatsLazyRouteImport = createFileRoute('/_layout/operations/seats')();
const LayoutOperationsPerformancesLazyRouteImport = createFileRoute('/_layout/operations/performances')();
const LayoutOperationsMerchantsLazyRouteImport = createFileRoute('/_layout/operations/merchants')();
const LayoutOperationsExceptionsLazyRouteImport = createFileRoute('/_layout/operations/exceptions')();
const LayoutGuideRoutesLazyRouteImport = createFileRoute('/_layout/guide/routes')();
const LayoutGuideHeatPointsLazyRouteImport = createFileRoute('/_layout/guide/heat-points')();
const LayoutGuideContentsLazyRouteImport = createFileRoute('/_layout/guide/contents')();
const LoginLazyRoute = LoginLazyRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
}).lazy(() => import('./routes/login.lazy').then((d) => d.Route));
const LayoutRoute = LayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => rootRouteImport,
});
const LayoutIndexLazyRoute = LayoutIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutRoute,
}).lazy(() => import('./routes/_layout/index.lazy').then((d) => d.Route));
const LayoutStatisticsLazyRoute = LayoutStatisticsLazyRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => LayoutRoute,
}).lazy(() => import('./routes/_layout/statistics.lazy').then((d) => d.Route));
const LayoutAuditLogsLazyRoute = LayoutAuditLogsLazyRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => LayoutRoute,
}).lazy(() => import('./routes/_layout/audit-logs.lazy').then((d) => d.Route));
const LayoutOperationsSeatsLazyRoute = LayoutOperationsSeatsLazyRouteImport.update({
    id: '/operations/seats',
    path: '/operations/seats',
    getParentRoute: () => LayoutRoute,
}).lazy(() => import('./routes/_layout/operations/seats.lazy').then((d) => d.Route));
const LayoutOperationsPerformancesLazyRoute = LayoutOperationsPerformancesLazyRouteImport.update({
    id: '/operations/performances',
    path: '/operations/performances',
    getParentRoute: () => LayoutRoute,
}).lazy(() => import('./routes/_layout/operations/performances.lazy').then((d) => d.Route));
const LayoutOperationsMerchantsLazyRoute = LayoutOperationsMerchantsLazyRouteImport.update({
    id: '/operations/merchants',
    path: '/operations/merchants',
    getParentRoute: () => LayoutRoute,
}).lazy(() => import('./routes/_layout/operations/merchants.lazy').then((d) => d.Route));
const LayoutOperationsExceptionsLazyRoute = LayoutOperationsExceptionsLazyRouteImport.update({
    id: '/operations/exceptions',
    path: '/operations/exceptions',
    getParentRoute: () => LayoutRoute,
}).lazy(() => import('./routes/_layout/operations/exceptions.lazy').then((d) => d.Route));
const LayoutGuideRoutesLazyRoute = LayoutGuideRoutesLazyRouteImport.update({
    id: '/guide/routes',
    path: '/guide/routes',
    getParentRoute: () => LayoutRoute,
}).lazy(() => import('./routes/_layout/guide/routes.lazy').then((d) => d.Route));
const LayoutGuideHeatPointsLazyRoute = LayoutGuideHeatPointsLazyRouteImport.update({
    id: '/guide/heat-points',
    path: '/guide/heat-points',
    getParentRoute: () => LayoutRoute,
}).lazy(() => import('./routes/_layout/guide/heat-points.lazy').then((d) => d.Route));
const LayoutGuideContentsLazyRoute = LayoutGuideContentsLazyRouteImport.update({
    id: '/guide/contents',
    path: '/guide/contents',
    getParentRoute: () => LayoutRoute,
}).lazy(() => import('./routes/_layout/guide/contents.lazy').then((d) => d.Route));
const LayoutRouteChildren = {
    LayoutAuditLogsLazyRoute: LayoutAuditLogsLazyRoute,
    LayoutStatisticsLazyRoute: LayoutStatisticsLazyRoute,
    LayoutIndexLazyRoute: LayoutIndexLazyRoute,
    LayoutGuideContentsLazyRoute: LayoutGuideContentsLazyRoute,
    LayoutGuideHeatPointsLazyRoute: LayoutGuideHeatPointsLazyRoute,
    LayoutGuideRoutesLazyRoute: LayoutGuideRoutesLazyRoute,
    LayoutOperationsExceptionsLazyRoute: LayoutOperationsExceptionsLazyRoute,
    LayoutOperationsMerchantsLazyRoute: LayoutOperationsMerchantsLazyRoute,
    LayoutOperationsPerformancesLazyRoute: LayoutOperationsPerformancesLazyRoute,
    LayoutOperationsSeatsLazyRoute: LayoutOperationsSeatsLazyRoute,
};
const LayoutRouteWithChildren = LayoutRoute._addFileChildren(LayoutRouteChildren);
const rootRouteChildren = {
    LayoutRoute: LayoutRouteWithChildren,
    LoginLazyRoute: LoginLazyRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
