/* eslint-disable */
/* prettier-ignore-start @ts-nocheck */
// This file is auto-generated by TanStack Router

// Import routes
import { Route as rootRoute } from './routes/__root';
import { Route as LayoutRoute } from './routes/_layout';
import { Route as LoginRouteImport } from './routes/login.lazy';
import { Route as LayoutIndexImport } from './routes/_layout/index.lazy';
import { Route as LayoutAuditLogsImport } from './routes/_layout/audit-logs.lazy';
import { Route as LayoutStatisticsImport } from './routes/_layout/statistics.lazy';
import { Route as LayoutOperationsExceptionsImport } from './routes/_layout/operations/exceptions.lazy';
import { Route as LayoutOperationsMerchantsImport } from './routes/_layout/operations/merchants.lazy';
import { Route as LayoutOperationsSeatsImport } from './routes/_layout/operations/seats.lazy';
import { Route as LayoutOperationsPerformancesImport } from './routes/_layout/operations/performances.lazy';
import { Route as LayoutGuideContentsImport } from './routes/_layout/guide/contents.lazy';
import { Route as LayoutGuideHeatPointsImport } from './routes/_layout/guide/heat-points.lazy';
import { Route as LayoutGuideRoutesImport } from './routes/_layout/guide/routes.lazy';

// Create/Update routes
const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any);
const LoginRoute = LoginRouteImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);
const LayoutAuditLogsRoute = LayoutAuditLogsImport.update({
  path: '/audit-logs',
  getParentRoute: () => LayoutRoute,
} as any);
const LayoutStatisticsRoute = LayoutStatisticsImport.update({
  path: '/statistics',
  getParentRoute: () => LayoutRoute,
} as any);
const LayoutOperationsExceptionsRoute = LayoutOperationsExceptionsImport.update({
  path: '/operations/exceptions',
  getParentRoute: () => LayoutRoute,
} as any);
const LayoutOperationsMerchantsRoute = LayoutOperationsMerchantsImport.update({
  path: '/operations/merchants',
  getParentRoute: () => LayoutRoute,
} as any);
const LayoutOperationsSeatsRoute = LayoutOperationsSeatsImport.update({
  path: '/operations/seats',
  getParentRoute: () => LayoutRoute,
} as any);
const LayoutOperationsPerformancesRoute = LayoutOperationsPerformancesImport.update({
  path: '/operations/performances',
  getParentRoute: () => LayoutRoute,
} as any);
const LayoutGuideContentsRoute = LayoutGuideContentsImport.update({
  path: '/guide/contents',
  getParentRoute: () => LayoutRoute,
} as any);
const LayoutGuideHeatPointsRoute = LayoutGuideHeatPointsImport.update({
  path: '/guide/heat-points',
  getParentRoute: () => LayoutRoute,
} as any);
const LayoutGuideRoutesRoute = LayoutGuideRoutesImport.update({
  path: '/guide/routes',
  getParentRoute: () => LayoutRoute,
} as any);

// Populate the file router
const routeTree = rootRoute.addChildren([
  LoginRoute,
  LayoutRoute.addChildren([
    LayoutIndexRoute,
    LayoutAuditLogsRoute,
    LayoutStatisticsRoute,
    LayoutOperationsExceptionsRoute,
    LayoutOperationsMerchantsRoute,
    LayoutOperationsSeatsRoute,
    LayoutOperationsPerformancesRoute,
    LayoutGuideContentsRoute,
    LayoutGuideHeatPointsRoute,
    LayoutGuideRoutesRoute,
  ]),
]);

export { routeTree };
/* prettier-ignore-end */
