# Generated by Django 4.2.7 on 2026-06-15 05:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributions', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0, verbose_name='完成百分比')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('distribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='distributions.distribution', verbose_name='发放记录')),
            ],
            options={
                'verbose_name': '学习进度',
                'verbose_name_plural': '学习进度',
                'db_table': 'progress',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='成绩')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='反馈')),
                ('graded_by', models.IntegerField(blank=True, null=True, verbose_name='评分人ID')),
                ('graded_at', models.DateTimeField(auto_now_add=True, verbose_name='评分时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.chapter', verbose_name='章节')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='progress_app.progress', verbose_name='学习进度')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'db_table': 'grade',
                'ordering': ['-graded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChapterCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='courses.chapter', verbose_name='章节')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_completions', to='progress_app.progress', verbose_name='学习进度')),
            ],
            options={
                'verbose_name': '章节完成记录',
                'verbose_name_plural': '章节完成记录',
                'db_table': 'chapter_completion',
            },
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['last_updated'], name='idx_progress_last_updated'),
        ),
        migrations.AlterUniqueTogether(
            name='chaptercompletion',
            unique_together={('progress', 'chapter')},
        ),
    ]
