# Generated by Django 4.2.7 on 2026-06-15 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='规则名称')),
                ('condition_type', models.CharField(choices=[('progress_below', '进度低于'), ('no_update_days', '未更新天数'), ('grade_below', '成绩低于')], max_length=50, verbose_name='触发条件类型')),
                ('threshold', models.IntegerField(verbose_name='阈值')),
                ('remind_method', models.CharField(choices=[('in_app', '站内'), ('email', '邮件'), ('both', '站内+邮件')], default='in_app', max_length=20, verbose_name='提醒方式')),
                ('frequency_days', models.IntegerField(default=7, verbose_name='提醒频次（天）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '提醒规则',
                'verbose_name_plural': '提醒规则',
                'db_table': 'reminder_rule',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='提醒内容')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reminders.reminderrule', verbose_name='提醒规则')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '提醒记录',
                'verbose_name_plural': '提醒记录',
                'db_table': 'reminder_log',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['student_id'], name='idx_reminder_log_student'), models.Index(fields=['is_read'], name='idx_reminder_log_read')],
            },
        ),
    ]
