import { defineNuxtPlugin } from '#imports'
import { setup } from '@css-render/vue3-ssr'
import {
  create,
  NButton,
  NInput,
  NSelect,
  NDatePicker,
  NForm,
  NFormItem,
  NModal,
  NCard,
  NTable,
  NDataTable,
  NPagination,
  NTag,
  NAlert,
  NDialogProvider,
  NMessageProvider,
  NNotificationProvider,
  NConfigProvider,
  NLayout,
  NLayoutSider,
  NLayoutHeader,
  NLayoutContent,
  NMenu,
  NGrid,
  NGi,
  NDrawer,
  NDrawerContent,
  NSpace,
  NDescriptions,
  NDescriptionsItem,
  NStatistic,
  NProgress,
  NImage,
  NUpload,
  NUploadDragger,
  NTabs,
  NTabPane,
  NTimeline,
  NTimelineItem,
  NBadge,
  NRate,
  NDivider,
  NEmpty,
  NPopover,
  NTooltip,
  NDropdown,
  NCheckbox,
  NCheckboxGroup,
  NRadio,
  NRadioGroup,
  NSwitch,
  NInputNumber,
  NSlider,
  NCascader,
  NTree,
  NTreeSelect,
  NTransfer,
  NMention,
  NAutoComplete,
  NColorPicker,
  NTimePicker,
  NTime,
  NThing,
  NSpin,
  NResult,
  NAvatar,
  NIcon,
  NGradientText,
  NEllipsis,
  NElement,
  NNumberAnimation,
  NH1,
  NH2,
  NH3,
  NH4,
  NText,
  NUl,
  NOl,
  NLi,
  NP,
  NBlockquote,
  NHr,
  NCode,
  NList,
  NListItem,
  NPageHeader,
  NBreadcrumb,
  NBreadcrumbItem,
  NSteps,
  NStep,
  NWaves,
  NCollapse,
  NCollapseItem,
  NCalendar,
  NCarousel,
  NWatermark,
  NCountdown,
  NAffix,
  NAnchor,
  NAnchorLink,
  NBackTop,
  NDynamicTags,
  NDynamicInput,
  NLog,
  NQrCode,
} from 'naive-ui'

const naive = create({
  components: [
    NButton, NInput, NSelect, NDatePicker, NForm, NFormItem, NModal, NCard,
    NTable, NDataTable, NPagination, NTag, NAlert, NDialogProvider,
    NMessageProvider, NNotificationProvider, NConfigProvider, NLayout,
    NLayoutSider, NLayoutHeader, NLayoutContent, NMenu, NGrid, NGi, NDrawer,
    NDrawerContent, NSpace, NDescriptions, NDescriptionsItem, NStatistic,
    NProgress, NImage, NUpload, NUploadDragger, NTabs, NTabPane, NTimeline,
    NTimelineItem, NBadge, NRate, NDivider, NEmpty, NPopover, NTooltip,
    NDropdown, NCheckbox, NCheckboxGroup, NRadio, NRadioGroup, NSwitch,
    NInputNumber, NSlider, NCascader, NTree, NTreeSelect, NTransfer,
    NMention, NAutoComplete, NColorPicker, NTimePicker, NTime, NThing,
    NSpin, NResult, NAvatar, NIcon, NGradientText, NEllipsis, NElement,
    NNumberAnimation, NH1, NH2, NH3, NH4, NText, NUl, NOl, NLi, NP,
    NBlockquote, NHr, NCode, NList, NListItem, NPageHeader, NBreadcrumb,
    NBreadcrumbItem, NSteps, NStep, NWaves, NCollapse, NCollapseItem,
    NCalendar, NCarousel, NWatermark, NCountdown, NAffix, NAnchor,
    NAnchorLink, NBackTop, NDynamicTags, NDynamicInput, NLog, NQrCode,
  ],
})

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(naive)
  if (import.meta.server) {
    const { collect } = setup(nuxtApp.vueApp)
    const originalRender = nuxtApp.ssrContext?.head?.tags
    nuxtApp.ssrContext!.head = nuxtApp.ssrContext!.head || {}
    const originalTagsGetter = Object.getOwnPropertyDescriptor(
      nuxtApp.ssrContext!.head,
      'tags'
    )?.get
    Object.defineProperty(nuxtApp.ssrContext!.head, 'tags', {
      get() {
        const result = typeof originalTagsGetter === 'function'
          ? originalTagsGetter()
          : []
        const style = collect()
        return [...result, {
          children: style,
          tag: 'style',
        }]
      },
    })
  }
})
