import { defineNuxtPlugin } from '#app'
import {
  NButton,
  NDataTable,
  NForm,
  NFormItem,
  NInput,
  NInputNumber,
  NSelect,
  NSpace,
  NTabPane,
  NTabs,
  NCard,
  NTag,
  NModal,
  NUpload,
  NUploadDragger,
  NCollapse,
  NCollapseItem,
  NTimeline,
  NTimelineItem,
  NDescriptions,
  NDescriptionsItem,
  NGrid,
  NGridItem,
  NStatistic,
  NBadge,
  NPopconfirm,
  NTooltip,
  NAvatar,
  NMenu,
  NLayout,
  NLayoutSider,
  NLayoutContent,
  NLayoutHeader,
  NBreadcrumb,
  NBreadcrumbItem,
  NDivider,
  NProgress,
  NImage,
  NImageGroup,
  NEmpty,
  NSpin,
  NResult,
  NConfigProvider,
  NMessageProvider,
  NDialogProvider,
  NNotificationProvider,
  NScrollbar,
  NText,
  NDropdown,
  NInputGroup,
  NDatePicker,
  NRadioGroup,
  NRadioButton,
  NRate,
  NPopselect,
  NCheckbox,
  NCheckboxGroup,
  NTransfer,
  NSwitch,
  NAlert,
  NPagination,
  NSkeleton,
  NListItem,
  NList,
  NThing,
  NAvatarGroup,
  NStep,
  NSteps,
  create,
} from 'naive-ui'

export default defineNuxtPlugin((nuxtApp) => {
  const naive = create({
    components: [
      NButton, NDataTable, NForm, NFormItem, NInput, NInputNumber,
      NSelect, NSpace, NTabPane, NTabs, NCard, NTag, NModal,
      NUpload, NUploadDragger, NCollapse, NCollapseItem, NTimeline,
      NTimelineItem, NDescriptions, NDescriptionsItem, NGrid, NGridItem,
      NStatistic, NBadge, NPopconfirm, NTooltip, NAvatar, NMenu,
      NLayout, NLayoutSider, NLayoutContent, NLayoutHeader, NBreadcrumb,
      NBreadcrumbItem, NDivider, NProgress, NImage, NImageGroup, NEmpty,
      NSpin, NResult, NConfigProvider, NMessageProvider, NDialogProvider,
      NNotificationProvider, NScrollbar, NText, NDropdown, NInputGroup, NDatePicker,
      NRadioGroup, NRadioButton, NRate, NPopselect, NCheckbox, NCheckboxGroup,
      NTransfer, NSwitch, NAlert, NPagination, NSkeleton, NListItem, NList,
      NThing, NAvatarGroup, NStep, NSteps,
    ],
  })
  nuxtApp.vueApp.use(naive)
})
