import { Supplier, Consumable } from './types';

export const SUPPLIERS: Supplier[] = [
  {
    id: 'SUP_A',
    name: '华美达日化',
    leadTime: 2,
    minOrderQty: 50,
    reliability: 0.95,
    priceMultiplier: 1.0,
    categories: ['洗发护理', '染膏', '烫发药水'],
  },
  {
    id: 'SUP_B',
    name: '丽姿美妆供应链',
    leadTime: 5,
    minOrderQty: 20,
    reliability: 0.80,
    priceMultiplier: 0.85,
    categories: ['洗发护理', '美甲用品', '护肤精油'],
  },
  {
    id: 'SUP_C',
    name: '顶尚专业线',
    leadTime: 3,
    minOrderQty: 30,
    reliability: 0.90,
    priceMultiplier: 0.92,
    categories: ['染膏', '烫发药水', '工具耗材'],
  },
  {
    id: 'SUP_D',
    name: '鑫源日化批发',
    leadTime: 7,
    minOrderQty: 100,
    reliability: 0.70,
    priceMultiplier: 0.75,
    categories: ['洗发护理', '染膏', '烫发药水', '美甲用品', '护肤精油', '工具耗材'],
  },
];

export const CONSUMABLES: Consumable[] = [
  {
    id: 'CON_01',
    name: '专业洗发露',
    category: '洗发护理',
    unit: '瓶',
    unitPrice: 28,
    safetyStock: 30,
    maxStock: 200,
    currentStock: 80,
    dailyUsage: 8,
    supplierIds: ['SUP_A', 'SUP_B', 'SUP_D'],
    batchNo: 'B2024-001',
    expiryDays: 365,
    receivedDate: 0,
  },
  {
    id: 'CON_02',
    name: '5/0染膏',
    category: '染膏',
    unit: '支',
    unitPrice: 45,
    safetyStock: 20,
    maxStock: 150,
    currentStock: 45,
    dailyUsage: 5,
    supplierIds: ['SUP_A', 'SUP_C', 'SUP_D'],
    batchNo: 'B2024-002',
    expiryDays: 270,
    receivedDate: 0,
  },
  {
    id: 'CON_03',
    name: '冷烫药水',
    category: '烫发药水',
    unit: '盒',
    unitPrice: 65,
    safetyStock: 15,
    maxStock: 100,
    currentStock: 30,
    dailyUsage: 3,
    supplierIds: ['SUP_A', 'SUP_C', 'SUP_D'],
    batchNo: 'B2024-003',
    expiryDays: 180,
    receivedDate: 0,
  },
  {
    id: 'CON_04',
    name: '甲油胶',
    category: '美甲用品',
    unit: '瓶',
    unitPrice: 18,
    safetyStock: 40,
    maxStock: 300,
    currentStock: 120,
    dailyUsage: 12,
    supplierIds: ['SUP_B', 'SUP_D'],
    batchNo: 'B2024-004',
    expiryDays: 365,
    receivedDate: 0,
  },
  {
    id: 'CON_05',
    name: '茶树精油',
    category: '护肤精油',
    unit: '瓶',
    unitPrice: 88,
    safetyStock: 10,
    maxStock: 60,
    currentStock: 25,
    dailyUsage: 2,
    supplierIds: ['SUP_B', 'SUP_D'],
    batchNo: 'B2024-005',
    expiryDays: 540,
    receivedDate: 0,
  },
  {
    id: 'CON_06',
    name: '一次性围布',
    category: '工具耗材',
    unit: '包',
    unitPrice: 12,
    safetyStock: 50,
    maxStock: 400,
    currentStock: 150,
    dailyUsage: 15,
    supplierIds: ['SUP_C', 'SUP_D'],
    batchNo: 'B2024-006',
    expiryDays: 9999,
    receivedDate: 0,
  },
];

export const ERROR_DESCRIPTIONS: Record<string, string> = {
  WRONG_SUPPLIER: '选错供应商，未综合考虑交期/最低量/可靠性',
  OVER_ORDER: '超额领用，超出合理用量',
  UNDER_ORDER: '领用不足，低于安全库存补货线',
  SAFETY_STOCK_BREACH: '安全库存被突破，门店有断货风险',
  EXPIRED_BATCH: '批次已过期或即将过期未处理',
  STOCKOUT: '耗材断货，门店运营受影响',
  INVENTORY_MISMATCH: '盘点数量差异未正确处理',
  LEAD_TIME_MISJUDGMENT: '未正确预估供应商交货周期',
};
