/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as ShortageRouteImport } from './routes/shortage'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShortageIndexRouteImport } from './routes/shortage/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as ShortageIdRouteImport } from './routes/shortage/$id'
import { Route as InventorySafetyRouteImport } from './routes/inventory/safety'
import { Route as InventoryBatchIdRouteImport } from './routes/inventory/$batchId'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortageRoute = ShortageRouteImport.update({
  id: '/shortage',
  path: '/shortage',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortageIndexRoute = ShortageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShortageRoute,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const ShortageIdRoute = ShortageIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShortageRoute,
} as any)
const InventorySafetyRoute = InventorySafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryBatchIdRoute = InventoryBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => InventoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/shortage': typeof ShortageRouteWithChildren
  '/suppliers': typeof SuppliersRoute
  '/inventory/$batchId': typeof InventoryBatchIdRoute
  '/inventory/safety': typeof InventorySafetyRoute
  '/shortage/$id': typeof ShortageIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/shortage/': typeof ShortageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/suppliers': typeof SuppliersRoute
  '/inventory/$batchId': typeof InventoryBatchIdRoute
  '/inventory/safety': typeof InventorySafetyRoute
  '/shortage/$id': typeof ShortageIdRoute
  '/inventory': typeof InventoryIndexRoute
  '/shortage': typeof ShortageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/shortage': typeof ShortageRouteWithChildren
  '/suppliers': typeof SuppliersRoute
  '/inventory/$batchId': typeof InventoryBatchIdRoute
  '/inventory/safety': typeof InventorySafetyRoute
  '/shortage/$id': typeof ShortageIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/shortage/': typeof ShortageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/inventory'
    | '/login'
    | '/rules'
    | '/shortage'
    | '/suppliers'
    | '/inventory/$batchId'
    | '/inventory/safety'
    | '/shortage/$id'
    | '/inventory/'
    | '/shortage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/login'
    | '/rules'
    | '/suppliers'
    | '/inventory/$batchId'
    | '/inventory/safety'
    | '/shortage/$id'
    | '/inventory'
    | '/shortage'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/inventory'
    | '/login'
    | '/rules'
    | '/shortage'
    | '/suppliers'
    | '/inventory/$batchId'
    | '/inventory/safety'
    | '/shortage/$id'
    | '/inventory/'
    | '/shortage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  LoginRoute: typeof LoginRoute
  RulesRoute: typeof RulesRoute
  ShortageRoute: typeof ShortageRouteWithChildren
  SuppliersRoute: typeof SuppliersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortage': {
      id: '/shortage'
      path: '/shortage'
      fullPath: '/shortage'
      preLoaderRoute: typeof ShortageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortage/': {
      id: '/shortage/'
      path: '/'
      fullPath: '/shortage/'
      preLoaderRoute: typeof ShortageIndexRouteImport
      parentRoute: typeof ShortageRoute
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/shortage/$id': {
      id: '/shortage/$id'
      path: '/$id'
      fullPath: '/shortage/$id'
      preLoaderRoute: typeof ShortageIdRouteImport
      parentRoute: typeof ShortageRoute
    }
    '/inventory/safety': {
      id: '/inventory/safety'
      path: '/safety'
      fullPath: '/inventory/safety'
      preLoaderRoute: typeof InventorySafetyRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/$batchId': {
      id: '/inventory/$batchId'
      path: '/$batchId'
      fullPath: '/inventory/$batchId'
      preLoaderRoute: typeof InventoryBatchIdRouteImport
      parentRoute: typeof InventoryRoute
    }
  }
}

interface InventoryRouteChildren {
  InventoryBatchIdRoute: typeof InventoryBatchIdRoute
  InventorySafetyRoute: typeof InventorySafetyRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryBatchIdRoute: InventoryBatchIdRoute,
  InventorySafetyRoute: InventorySafetyRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface ShortageRouteChildren {
  ShortageIdRoute: typeof ShortageIdRoute
  ShortageIndexRoute: typeof ShortageIndexRoute
}

const ShortageRouteChildren: ShortageRouteChildren = {
  ShortageIdRoute: ShortageIdRoute,
  ShortageIndexRoute: ShortageIndexRoute,
}

const ShortageRouteWithChildren = ShortageRoute._addFileChildren(
  ShortageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRouteWithChildren,
  LoginRoute: LoginRoute,
  RulesRoute: RulesRoute,
  ShortageRoute: ShortageRouteWithChildren,
  SuppliersRoute: SuppliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
