# Generated by Django 4.2.7 on 2026-06-15 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='教材标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='教材描述')),
                ('file_url', models.CharField(blank=True, default='', max_length=500, verbose_name='文件地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='courses.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '教材',
                'verbose_name_plural': '教材',
                'db_table': 'material',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#1B3A5C', max_length=7, verbose_name='标签颜色')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tag',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='教材')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '教材标签',
                'verbose_name_plural': '教材标签',
                'db_table': 'material_tags',
                'unique_together': {('material', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='material',
            name='tags',
            field=models.ManyToManyField(related_name='materials', through='materials.MaterialTag', to='materials.tag', verbose_name='标签'),
        ),
    ]
