import { PrismaClient, UserRole, ChangeOrderStatus, MaterialDelayStatus, AfterSalesStatus, AcceptanceStatus, LogAction } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();
const SALT_ROUNDS = 10;

async function main() {
  console.log('开始播种数据...');

  const hashedPassword = await bcrypt.hash('123456', SALT_ROUNDS);

  const owner = await prisma.user.upsert({
    where: { email: 'owner@test.com' },
    update: {},
    create: {
      email: 'owner@test.com',
      phone: '13800000001',
      name: '张业主',
      password: hashedPassword,
      role: UserRole.OWNER,
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=owner',
    },
  });

  const designer = await prisma.user.upsert({
    where: { email: 'designer@test.com' },
    update: {},
    create: {
      email: 'designer@test.com',
      phone: '13800000002',
      name: '李设计师',
      password: hashedPassword,
      role: UserRole.DESIGNER,
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=designer',
    },
  });

  const foreman = await prisma.user.upsert({
    where: { email: 'foreman@test.com' },
    update: {},
    create: {
      email: 'foreman@test.com',
      phone: '13800000003',
      name: '王工长',
      password: hashedPassword,
      role: UserRole.FOREMAN,
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=foreman',
    },
  });

  const supervisor = await prisma.user.upsert({
    where: { email: 'supervisor@test.com' },
    update: {},
    create: {
      email: 'supervisor@test.com',
      phone: '13800000004',
      name: '赵监理',
      password: hashedPassword,
      role: UserRole.SUPERVISOR,
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=supervisor',
    },
  });

  console.log('用户创建完成');

  const project1 = await prisma.project.upsert({
    where: { id: 'proj-cuid-001' },
    update: {},
    create: {
      id: 'proj-cuid-001',
      name: '阳光花园3栋201室装修项目',
      address: '北京市朝阳区阳光花园3号楼2单元201室',
      ownerId: owner.id,
      designerId: designer.id,
      foremanId: foreman.id,
      supervisorId: supervisor.id,
      startDate: new Date('2024-01-15'),
      endDate: new Date('2024-06-30'),
      status: 'ACTIVE',
      description: '三室两厅两卫，建筑面积120平米，现代简约风格整装',
    },
  });

  const project2 = await prisma.project.upsert({
    where: { id: 'proj-cuid-002' },
    update: {},
    create: {
      id: 'proj-cuid-002',
      name: '翠湖天地5栋1502室装修项目',
      address: '上海市浦东新区翠湖天地5号楼1单元1502室',
      ownerId: owner.id,
      designerId: designer.id,
      foremanId: foreman.id,
      supervisorId: supervisor.id,
      startDate: new Date('2024-03-01'),
      endDate: new Date('2024-09-30'),
      status: 'ACTIVE',
      description: '两室一厅一卫，建筑面积85平米，北欧风格精装修',
    },
  });

  const project3 = await prisma.project.upsert({
    where: { id: 'proj-cuid-003' },
    update: {},
    create: {
      id: 'proj-cuid-003',
      name: '金色家园别墅装修项目',
      address: '深圳市南山区金色家园别墅区A座',
      ownerId: owner.id,
      designerId: designer.id,
      foremanId: foreman.id,
      supervisorId: supervisor.id,
      startDate: new Date('2023-10-01'),
      endDate: new Date('2024-12-31'),
      actualEndDate: null,
      status: 'ACTIVE',
      description: '独栋别墅，建筑面积380平米，新中式风格豪华装修',
    },
  });

  console.log('项目创建完成');

  const changeOrders = [
    {
      id: 'co-cuid-001',
      orderNo: 'CO-2024-001',
      projectId: project1.id,
      title: '主卧背景墙造型调整',
      description: '业主要求将主卧背景墙从乳胶漆改为硬包造型，增加灯带效果',
      reason: '业主个人审美偏好变化',
      originalDesign: '白色乳胶漆墙面',
      newDesign: '米色硬包背景墙+LED灯带+金属收边条',
      impactOnSchedule: 3,
      impactOnCost: 8500.00,
      status: ChangeOrderStatus.ACCEPTED,
      designerId: designer.id,
      submittedById: designer.id,
      approvedAt: new Date('2024-02-10'),
      completedAt: new Date('2024-02-25'),
      deadline: new Date('2024-02-28'),
    },
    {
      id: 'co-cuid-002',
      orderNo: 'CO-2024-002',
      projectId: project1.id,
      title: '卫生间防滑砖更换',
      description: '将卫生间地砖从普通抛光砖更换为防滑仿古砖',
      reason: '安全考虑，防止滑倒',
      originalDesign: '600x600白色抛光砖',
      newDesign: '600x600灰色防滑仿古砖',
      impactOnSchedule: 2,
      impactOnCost: 3200.00,
      status: ChangeOrderStatus.IN_PROGRESS,
      designerId: designer.id,
      submittedById: foreman.id,
      approvedAt: new Date('2024-03-05'),
      deadline: new Date('2024-03-20'),
    },
    {
      id: 'co-cuid-003',
      orderNo: 'CO-2024-003',
      projectId: project1.id,
      title: '厨房橱柜布局优化',
      description: '调整厨房橱柜布局，增加高柜，优化动线',
      reason: '使用体验优化',
      originalDesign: 'L型橱柜+地柜+吊柜',
      newDesign: 'U型橱柜+高柜+抽屉篮+调味篮',
      impactOnSchedule: 5,
      impactOnCost: 12000.00,
      status: ChangeOrderStatus.OWNER_APPROVED,
      designerId: designer.id,
      submittedById: designer.id,
      approvedAt: new Date('2024-03-15'),
      deadline: new Date('2024-04-10'),
    },
    {
      id: 'co-cuid-004',
      orderNo: 'CO-2024-004',
      projectId: project2.id,
      title: '客厅吊顶造型变更',
      description: '将客厅平面吊顶改为跌级吊顶，增加中央空调出风口',
      reason: '加装中央空调',
      originalDesign: '平面石膏板吊顶',
      newDesign: '跌级石膏板吊顶+中央空调出风口+筒灯',
      impactOnSchedule: 7,
      impactOnCost: 15800.00,
      status: ChangeOrderStatus.PENDING_REVIEW,
      designerId: designer.id,
      submittedById: owner.id,
      deadline: new Date('2024-04-15'),
    },
    {
      id: 'co-cuid-005',
      orderNo: 'CO-2024-005',
      projectId: project2.id,
      title: '阳台封闭改造',
      description: '将开放式阳台改为封闭阳台，加装断桥铝窗户',
      reason: '隔音防尘需求',
      originalDesign: '开放式阳台+铁艺栏杆',
      newDesign: '封闭阳台+断桥铝双层玻璃窗+大理石窗台',
      impactOnSchedule: 4,
      impactOnCost: 9600.00,
      status: ChangeOrderStatus.DESIGNER_APPROVED,
      designerId: designer.id,
      submittedById: owner.id,
      approvedAt: new Date('2024-03-20'),
      deadline: new Date('2024-04-05'),
    },
    {
      id: 'co-cuid-006',
      orderNo: 'CO-2024-006',
      projectId: project2.id,
      title: '主卫智能马桶加装',
      description: '增加智能马桶盖及配套水电改造',
      reason: '提升生活品质',
      originalDesign: '普通马桶',
      newDesign: '智能马桶盖+预留插座+进水改造',
      impactOnSchedule: 1,
      impactOnCost: 2800.00,
      status: ChangeOrderStatus.DRAFT,
      designerId: designer.id,
      submittedById: designer.id,
    },
    {
      id: 'co-cuid-007',
      orderNo: 'CO-2024-007',
      projectId: project3.id,
      title: '地下室影音室设计变更',
      description: '重新设计地下室影音室，增加声学处理和专业投影系统',
      reason: '功能升级需求',
      originalDesign: '简易家庭娱乐室',
      newDesign: '专业影音室+声学处理+4K投影+7.1声道音响+观影沙发',
      impactOnSchedule: 15,
      impactOnCost: 85000.00,
      status: ChangeOrderStatus.PENDING_ACCEPTANCE,
      designerId: designer.id,
      submittedById: designer.id,
      approvedAt: new Date('2024-01-20'),
      completedAt: new Date('2024-03-10'),
      deadline: new Date('2024-03-15'),
    },
    {
      id: 'co-cuid-008',
      orderNo: 'CO-2024-008',
      projectId: project3.id,
      title: '花园景观设计调整',
      description: '调整后花园景观设计，增加水景和休闲区',
      reason: '业主对初版设计不满意',
      originalDesign: '简单草坪+灌木',
      newDesign: '假山流水+木质平台+休闲桌椅+观赏鱼池+花境',
      impactOnSchedule: 10,
      impactOnCost: 35000.00,
      status: ChangeOrderStatus.REJECTED,
      designerId: designer.id,
      submittedById: owner.id,
      approvedAt: null,
      deadline: new Date('2024-05-01'),
    },
  ];

  for (const co of changeOrders) {
    await prisma.designChangeOrder.upsert({
      where: { id: co.id },
      update: {},
      create: co,
    });
  }

  console.log('设计变更单创建完成');

  const materialDelays = [
    {
      id: 'md-cuid-001',
      changeOrderId: 'co-cuid-002',
      projectId: project1.id,
      materialName: '防滑仿古砖',
      specification: '600x600mm 灰色',
      quantity: 120,
      originalDate: new Date('2024-03-08'),
      estimatedDate: new Date('2024-03-15'),
      actualDate: null,
      delayDays: 7,
      reason: '厂家库存不足，需从外地调货',
      status: MaterialDelayStatus.CONFIRMED,
      impact: '卫生间瓦工工序延后3天',
      reportedById: foreman.id,
      handledById: designer.id,
    },
    {
      id: 'md-cuid-002',
      changeOrderId: 'co-cuid-004',
      projectId: project2.id,
      materialName: '中央空调室内机',
      specification: '1.5匹 变频',
      quantity: 3,
      originalDate: new Date('2024-03-25'),
      estimatedDate: new Date('2024-04-01'),
      actualDate: null,
      delayDays: 7,
      reason: '物流运输延误，高速封路',
      status: MaterialDelayStatus.REPORTED,
      impact: '吊顶安装工序延后',
      reportedById: foreman.id,
      handledById: null,
    },
    {
      id: 'md-cuid-003',
      changeOrderId: null,
      projectId: project1.id,
      materialName: '定制木门',
      specification: '卧室门 3扇',
      quantity: 3,
      originalDate: new Date('2024-02-20'),
      estimatedDate: new Date('2024-03-05'),
      actualDate: new Date('2024-03-03'),
      delayDays: 11,
      reason: '春节假期工厂停工，交货延后',
      status: MaterialDelayStatus.RESOLVED,
      impact: '油漆工序整体延后5天',
      reportedById: foreman.id,
      handledById: supervisor.id,
    },
    {
      id: 'md-cuid-004',
      changeOrderId: 'co-cuid-007',
      projectId: project3.id,
      materialName: '投影幕布',
      specification: '120寸 电动拉线幕',
      quantity: 1,
      originalDate: new Date('2024-02-28'),
      estimatedDate: new Date('2024-03-20'),
      actualDate: null,
      delayDays: 20,
      reason: '进口产品清关延误',
      status: MaterialDelayStatus.RESCHEDULED,
      impact: '影音室验收延后',
      reportedById: designer.id,
      handledById: supervisor.id,
    },
    {
      id: 'md-cuid-005',
      changeOrderId: null,
      projectId: project3.id,
      materialName: '大理石台面',
      specification: '厨房台面 石英石',
      quantity: 8.5,
      originalDate: new Date('2024-03-10'),
      estimatedDate: new Date('2024-03-25'),
      actualDate: new Date('2024-03-22'),
      delayDays: 12,
      reason: '石材色差问题，重新加工',
      status: MaterialDelayStatus.CLOSED,
      impact: '橱柜安装延后一周',
      reportedById: foreman.id,
      handledById: supervisor.id,
    },
  ];

  for (const md of materialDelays) {
    await prisma.materialDelay.upsert({
      where: { id: md.id },
      update: {},
      create: md,
    });
  }

  console.log('材料延期记录创建完成');

  const acceptancePhotos = [
    {
      id: 'ap-cuid-001',
      changeOrderId: 'co-cuid-001',
      uploaderId: foreman.id,
      photoUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=200',
      description: '主卧背景墙硬包完成效果',
      status: AcceptanceStatus.PASSED,
      reviewRemark: '工艺精良，符合设计要求',
      reviewedById: supervisor.id,
      reviewedAt: new Date('2024-02-25'),
      phase: '完成验收',
    },
    {
      id: 'ap-cuid-002',
      changeOrderId: 'co-cuid-001',
      uploaderId: foreman.id,
      photoUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=200',
      description: '背景墙灯带效果展示',
      status: AcceptanceStatus.PASSED,
      reviewRemark: '灯光效果均匀柔和',
      reviewedById: supervisor.id,
      reviewedAt: new Date('2024-02-25'),
      phase: '完成验收',
    },
    {
      id: 'ap-cuid-003',
      changeOrderId: 'co-cuid-002',
      uploaderId: foreman.id,
      photoUrl: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=200',
      description: '卫生间防滑砖铺贴中',
      status: AcceptanceStatus.PENDING,
      reviewRemark: null,
      reviewedById: null,
      reviewedAt: null,
      phase: '中期检查',
    },
    {
      id: 'ap-cuid-004',
      changeOrderId: 'co-cuid-002',
      uploaderId: foreman.id,
      photoUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=200',
      description: '卫生间防水处理',
      status: AcceptanceStatus.FAILED,
      reviewRemark: '墙角防水处理不到位，需返工',
      reviewedById: supervisor.id,
      reviewedAt: new Date('2024-03-12'),
      phase: '隐蔽工程验收',
    },
    {
      id: 'ap-cuid-005',
      changeOrderId: 'co-cuid-003',
      uploaderId: designer.id,
      photoUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=200',
      description: '厨房U型橱柜设计图',
      status: AcceptanceStatus.PENDING,
      reviewRemark: null,
      reviewedById: null,
      reviewedAt: null,
      phase: '设计确认',
    },
    {
      id: 'ap-cuid-006',
      changeOrderId: 'co-cuid-007',
      uploaderId: foreman.id,
      photoUrl: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=200',
      description: '影音室声学处理施工',
      status: AcceptanceStatus.RE_INSPECTED,
      reviewRemark: '第一次验收隔音效果不达标，返工后重新验收',
      reviewedById: supervisor.id,
      reviewedAt: new Date('2024-03-08'),
      phase: '隐蔽工程',
    },
    {
      id: 'ap-cuid-007',
      changeOrderId: 'co-cuid-007',
      uploaderId: foreman.id,
      photoUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=200',
      description: '投影设备安装调试',
      status: AcceptanceStatus.PENDING,
      reviewRemark: null,
      reviewedById: null,
      reviewedAt: null,
      phase: '设备安装',
    },
    {
      id: 'ap-cuid-008',
      changeOrderId: 'co-cuid-005',
      uploaderId: foreman.id,
      photoUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=200',
      description: '阳台窗户框架安装',
      status: AcceptanceStatus.PASSED,
      reviewRemark: '安装牢固，密封良好',
      reviewedById: supervisor.id,
      reviewedAt: new Date('2024-03-28'),
      phase: '框架安装验收',
    },
    {
      id: 'ap-cuid-009',
      changeOrderId: 'co-cuid-005',
      uploaderId: foreman.id,
      photoUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=200',
      description: '阳台大理石窗台铺贴',
      status: AcceptanceStatus.PENDING,
      reviewRemark: null,
      reviewedById: null,
      reviewedAt: null,
      phase: '装修施工',
    },
    {
      id: 'ap-cuid-010',
      changeOrderId: 'co-cuid-003',
      uploaderId: designer.id,
      photoUrl: 'https://images.unsplash.com/photo-1556910103-1c022119f1ef?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1556910103-1c022119f1ef?w=200',
      description: '橱柜五金配件样品',
      status: AcceptanceStatus.PASSED,
      reviewRemark: '品牌确认无误，质量合格',
      reviewedById: owner.id,
      reviewedAt: new Date('2024-03-18'),
      phase: '材料确认',
    },
  ];

  for (const ap of acceptancePhotos) {
    await prisma.acceptancePhoto.upsert({
      where: { id: ap.id },
      update: {},
      create: ap,
    });
  }

  console.log('验收照片创建完成');

  const workerCheckins = [
    {
      id: 'wc-cuid-001',
      projectId: project1.id,
      workerId: foreman.id,
      checkinTime: new Date('2024-03-18T08:00:00'),
      checkoutTime: new Date('2024-03-18T18:00:00'),
      location: '阳光花园3栋201',
      photoUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
      remark: '今日进行瓦工施工，卫生间贴砖',
      workType: '瓦工',
    },
    {
      id: 'wc-cuid-002',
      projectId: project1.id,
      workerId: foreman.id,
      checkinTime: new Date('2024-03-19T07:30:00'),
      checkoutTime: new Date('2024-03-19T17:30:00'),
      location: '阳光花园3栋201',
      photoUrl: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400',
      remark: '继续卫生间贴砖工作',
      workType: '瓦工',
    },
    {
      id: 'wc-cuid-003',
      projectId: project2.id,
      workerId: foreman.id,
      checkinTime: new Date('2024-03-18T08:30:00'),
      checkoutTime: new Date('2024-03-18T19:00:00'),
      location: '翠湖天地5栋1502',
      photoUrl: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400',
      remark: '水电改造施工，今日完成客厅和卧室布线',
      workType: '水电',
    },
    {
      id: 'wc-cuid-004',
      projectId: project2.id,
      workerId: foreman.id,
      checkinTime: new Date('2024-03-20T08:00:00'),
      checkoutTime: null,
      location: '翠湖天地5栋1502',
      photoUrl: 'https://images.unsplash.com/photo-1581094271901-8022df4466f9?w=400',
      remark: '木工进场，开始吊顶龙骨安装',
      workType: '木工',
    },
    {
      id: 'wc-cuid-005',
      projectId: project3.id,
      workerId: foreman.id,
      checkinTime: new Date('2024-03-17T07:00:00'),
      checkoutTime: new Date('2024-03-17T18:30:00'),
      location: '金色家园别墅区A座',
      photoUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
      remark: '影音室隔音棉安装，进度约60%',
      workType: '隔音工程',
    },
    {
      id: 'wc-cuid-006',
      projectId: project3.id,
      workerId: foreman.id,
      checkinTime: new Date('2024-03-19T07:30:00'),
      checkoutTime: new Date('2024-03-19T17:00:00'),
      location: '金色家园别墅区A座',
      photoUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400',
      remark: '厨房橱柜测量复尺，准备下单生产',
      workType: '测量',
    },
  ];

  for (const wc of workerCheckins) {
    await prisma.workerCheckin.upsert({
      where: { id: wc.id },
      update: {},
      create: wc,
    });
  }

  console.log('工人签到记录创建完成');

  const afterSalesTickets = [
    {
      id: 'ast-cuid-001',
      ticketNo: 'AS-2024-001',
      projectId: project1.id,
      title: '主卧墙面开裂',
      description: '主卧背景墙右侧墙面出现约30cm长的裂缝，需要修补',
      status: AfterSalesStatus.IN_PROGRESS,
      priority: 'HIGH',
      reporterId: owner.id,
      assigneeId: foreman.id,
      resolvedAt: null,
    },
    {
      id: 'ast-cuid-002',
      ticketNo: 'AS-2024-002',
      projectId: project1.id,
      title: '卫生间水龙头漏水',
      description: '客卫洗手台水龙头关不严，有滴水现象',
      status: AfterSalesStatus.RESOLVED,
      priority: 'NORMAL',
      reporterId: owner.id,
      assigneeId: foreman.id,
      resolvedAt: new Date('2024-03-10'),
    },
    {
      id: 'ast-cuid-003',
      ticketNo: 'AS-2024-003',
      projectId: project2.id,
      title: '阳台窗户密封不严',
      description: '刮风天气阳台窗户有明显漏风现象，隔音效果差',
      status: AfterSalesStatus.OPEN,
      priority: 'NORMAL',
      reporterId: owner.id,
      assigneeId: null,
      resolvedAt: null,
    },
    {
      id: 'ast-cuid-004',
      ticketNo: 'AS-2024-004',
      projectId: project3.id,
      title: '地下室潮湿问题',
      description: '雨季地下室墙面有返潮现象，需检查防水处理',
      status: AfterSalesStatus.PENDING_REVIEW,
      priority: 'HIGH',
      reporterId: owner.id,
      assigneeId: supervisor.id,
      resolvedAt: null,
    },
  ];

  for (const ast of afterSalesTickets) {
    await prisma.afterSalesTicket.upsert({
      where: { id: ast.id },
      update: {},
      create: ast,
    });
  }

  console.log('售后工单创建完成');

  const operationLogs = [
    {
      id: 'ol-cuid-001',
      action: LogAction.CREATE,
      entityType: 'DesignChangeOrder',
      entityId: 'co-cuid-001',
      oldValue: null,
      newValue: JSON.stringify({ title: '主卧背景墙造型调整', status: 'DRAFT' }),
      remark: '创建设计变更单',
      operatorId: designer.id,
    },
    {
      id: 'ol-cuid-002',
      action: LogAction.STATUS_CHANGE,
      entityType: 'DesignChangeOrder',
      entityId: 'co-cuid-001',
      oldValue: 'DRAFT',
      newValue: 'PENDING_REVIEW',
      remark: '提交审核',
      operatorId: designer.id,
    },
    {
      id: 'ol-cuid-003',
      action: LogAction.STATUS_CHANGE,
      entityType: 'DesignChangeOrder',
      entityId: 'co-cuid-001',
      oldValue: 'PENDING_REVIEW',
      newValue: 'DESIGNER_APPROVED',
      remark: '设计师审核通过',
      operatorId: designer.id,
    },
    {
      id: 'ol-cuid-004',
      action: LogAction.STATUS_CHANGE,
      entityType: 'DesignChangeOrder',
      entityId: 'co-cuid-001',
      oldValue: 'DESIGNER_APPROVED',
      newValue: 'OWNER_APPROVED',
      remark: '业主确认同意',
      operatorId: owner.id,
    },
    {
      id: 'ol-cuid-005',
      action: LogAction.STATUS_CHANGE,
      entityType: 'DesignChangeOrder',
      entityId: 'co-cuid-001',
      oldValue: 'OWNER_APPROVED',
      newValue: 'IN_PROGRESS',
      remark: '开始施工',
      operatorId: foreman.id,
    },
    {
      id: 'ol-cuid-006',
      action: LogAction.STATUS_CHANGE,
      entityType: 'DesignChangeOrder',
      entityId: 'co-cuid-001',
      oldValue: 'IN_PROGRESS',
      newValue: 'PENDING_ACCEPTANCE',
      remark: '施工完成，申请验收',
      operatorId: foreman.id,
    },
    {
      id: 'ol-cuid-007',
      action: LogAction.STATUS_CHANGE,
      entityType: 'DesignChangeOrder',
      entityId: 'co-cuid-001',
      oldValue: 'PENDING_ACCEPTANCE',
      newValue: 'ACCEPTED',
      remark: '监理验收通过',
      operatorId: supervisor.id,
    },
    {
      id: 'ol-cuid-008',
      action: LogAction.CREATE,
      entityType: 'DesignChangeOrder',
      entityId: 'co-cuid-002',
      oldValue: null,
      newValue: JSON.stringify({ title: '卫生间防滑砖更换', status: 'DRAFT' }),
      remark: '创建设计变更单',
      operatorId: foreman.id,
    },
    {
      id: 'ol-cuid-009',
      action: LogAction.CREATE,
      entityType: 'MaterialDelay',
      entityId: 'md-cuid-001',
      oldValue: null,
      newValue: JSON.stringify({ materialName: '防滑仿古砖', status: 'REPORTED' }),
      remark: '上报材料延期',
      operatorId: foreman.id,
    },
    {
      id: 'ol-cuid-010',
      action: LogAction.STATUS_CHANGE,
      entityType: 'MaterialDelay',
      entityId: 'md-cuid-001',
      oldValue: 'REPORTED',
      newValue: 'CONFIRMED',
      remark: '确认材料延期',
      operatorId: supervisor.id,
    },
    {
      id: 'ol-cuid-011',
      action: LogAction.CREATE,
      entityType: 'AcceptancePhoto',
      entityId: 'ap-cuid-001',
      oldValue: null,
      newValue: JSON.stringify({ description: '主卧背景墙硬包完成效果', status: 'PENDING' }),
      remark: '上传验收照片',
      operatorId: foreman.id,
    },
    {
      id: 'ol-cuid-012',
      action: LogAction.STATUS_CHANGE,
      entityType: 'AcceptancePhoto',
      entityId: 'ap-cuid-001',
      oldValue: 'PENDING',
      newValue: 'PASSED',
      remark: '照片审核通过',
      operatorId: supervisor.id,
    },
    {
      id: 'ol-cuid-013',
      action: LogAction.CREATE,
      entityType: 'AfterSalesTicket',
      entityId: 'ast-cuid-001',
      oldValue: null,
      newValue: JSON.stringify({ title: '主卧墙面开裂', status: 'OPEN' }),
      remark: '提交售后工单',
      operatorId: owner.id,
    },
    {
      id: 'ol-cuid-014',
      action: LogAction.STATUS_CHANGE,
      entityType: 'AfterSalesTicket',
      entityId: 'ast-cuid-001',
      oldValue: 'OPEN',
      newValue: 'IN_PROGRESS',
      remark: '分配给工长处理',
      operatorId: supervisor.id,
    },
    {
      id: 'ol-cuid-015',
      action: LogAction.STATUS_CHANGE,
      entityType: 'AfterSalesTicket',
      entityId: 'ast-cuid-002',
      oldValue: 'IN_PROGRESS',
      newValue: 'RESOLVED',
      remark: '问题已解决',
      operatorId: foreman.id,
    },
    {
      id: 'ol-cuid-016',
      action: LogAction.UPDATE,
      entityType: 'Project',
      entityId: project1.id,
      oldValue: JSON.stringify({ status: 'PLANNING' }),
      newValue: JSON.stringify({ status: 'ACTIVE' }),
      remark: '项目正式开工',
      operatorId: supervisor.id,
    },
    {
      id: 'ol-cuid-017',
      action: LogAction.CREATE,
      entityType: 'WorkerCheckin',
      entityId: 'wc-cuid-001',
      oldValue: null,
      newValue: JSON.stringify({ workType: '瓦工', checkinTime: '2024-03-18T08:00:00' }),
      remark: '工人签到',
      operatorId: foreman.id,
    },
    {
      id: 'ol-cuid-018',
      action: LogAction.COMMENT,
      entityType: 'DesignChangeOrder',
      entityId: 'co-cuid-004',
      oldValue: null,
      newValue: '请尽快审核吊顶变更方案，谢谢！',
      remark: '业主留言催促',
      operatorId: owner.id,
    },
    {
      id: 'ol-cuid-019',
      action: LogAction.STATUS_CHANGE,
      entityType: 'DesignChangeOrder',
      entityId: 'co-cuid-008',
      oldValue: 'PENDING_REVIEW',
      newValue: 'REJECTED',
      remark: '变更费用过高，暂不实施',
      operatorId: owner.id,
    },
    {
      id: 'ol-cuid-020',
      action: LogAction.UPDATE,
      entityType: 'MaterialDelay',
      entityId: 'md-cuid-003',
      oldValue: JSON.stringify({ status: 'CONFIRMED' }),
      newValue: JSON.stringify({ status: 'RESOLVED', actualDate: '2024-03-03' }),
      remark: '材料已送达，延期问题解决',
      operatorId: foreman.id,
    },
  ];

  for (const ol of operationLogs) {
    await prisma.operationLog.upsert({
      where: { id: ol.id },
      update: {},
      create: ol,
    });
  }

  console.log('操作日志创建完成');

  console.log('所有种子数据播种完成！');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
